#!/usr/bin/env bash

# GitHub-ready entrypoint copied from the development workspace.
# Machine-specific tools and references are resolved from config/pipeline.env.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
export SPATIAL_EPIGENOME_REPO_ROOT="${repo_root}"
# shellcheck source=../lib/common.sh
source "${repo_root}/lib/common.sh"
load_pipeline_config "${repo_root}"
SLURM_CPUS_PER_TASK="${SLURM_CPUS_PER_TASK:-$(threads_or_default 4)}"



set -e
set -o pipefail

helpdoc() {
    cat <<EOF
Description:
    [main::] Spatial 5hmC of DBiT-seq processing pipeline created by Maoxu Wang, Xie Lab, Peking University.
    Last update: 2024.11.30
Usage:
    $run [options]
        -h print user manual information
Options:
    --read1             -- Read1 (.fastq.gz)
    --read2             -- Read2 (.fastq.gz)
    --sampleid          -- sampleid name specified 
    --species           -- e.g. hg38 or mm10
    --decode_file       -- generated by DBiT chip
    --n_line            -- number of lines to process (default: all lines)
    --outdir            -- output directory
    --img               -- fluorescence or HE image
    --option            -- steps to run
    --debug             -- debug mode
    --help              -- print manual
EOF
}
ARGS=$(getopt -o o:i:h -l read1:,read2:,sampleid:,species:,decode_file:,n_line:,outdir:,img:,option:,debug:,paired:,mode:,help -- "$@")



if [ $? != 0 ]; then
    echo "terminating..." >&2
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
    --read1)
        read1=$2
        shift 2
        ;;
    --read2)
        read2=$2
        shift 2
        ;; 
    --sampleid)
        sampleid=$2
        shift 2
        ;; 
    --species)
        species=$2
        shift 2
        ;; 
    --decode_file)
        decode_file=$2
        shift 2
        ;;  
    --n_line)
        n_line=$2
        shift 2
        ;;
    -o | --outdir)
        outdir=$2
        shift 2
        ;;
    --img)
        img=$2
        shift 2
        ;;
    --option)
        option=$2
        shift 2
        ;;
    --debug)
        debug=$2
        shift 2
        ;;
    --paired)
        paired=$2
        shift 2
        ;;
    --mode)
        mode=$2
        shift 2
        ;;
    -h | --help)
        helpdoc
        exit 1
        ;;
    --)
        shift
        echo "Parameters recevied."
        break
        ;;
    *)
        echo "unknown parameter:" $1
        helpdoc
        exit 1
        ;;
    esac
done

## ---- inspect arguments ---

if [[ ! -n $outdir ]]; then outdir="./result"; fi
if [[ ! -n $n_line ]]; then n_line="-1"; fi
if [[ ! -n $option ]]; then option="pipe"; fi
if [[ ! -n $paired ]]; then paired="FALSE"; fi
if [[ ! -n $mode ]]; then mode="atac"; fi

if [[ ! -n $decode_file ]]; then 
    decode_file="${DBIT_DECODE_FILE:-${repo_root}/resources/DBiT/spatial_barcodes.txt}"
fi

if [[ ! -n $debug ]]; then debug=False; fi

if [[ ! -n $sampleid ]]; then
    echo "Please specify sampleid name"
    exit
fi

if [[ ! -n $species ]]; then
    echo "Please specify species"
    exit
fi

if [[ $SLURM_CPUS_PER_TASK > 12 ]];then 
    sort_thread=12
else
    sort_thread=$SLURM_CPUS_PER_TASK
fi 


## ---- SOFTWARE --- 
trim_galore="${TRIM_GALORE:-trim_galore}"
cutadapt="${CUTADAPT:-cutadapt}"
bedtools="${BEDTOOLS:-bedtools}"
bowtie2="${BOWTIE2:-bowtie2}"
samtools="${SAMTOOLS:-samtools}"
src="${SPATIAL_EPIGENOME_SCRIPT_DIR:-${repo_root}/scripts}/DBiT"
umi_tools="${UMI_TOOLS:-umi_tools}"
spatial_IVT="${SPATIAL_IVT:-spatial_IVT}"
seqkit="${SEQKIT:-seqkit}"
python="${PYTHON:-python}"
python_cv2="${PYTHON_CV2:-python}"
merge_super_spot="${MERGE_SUPER_SPOT:-levelMatrix.py}"
picard="${PICARD:-picard}"
Rscript="${RSCRIPT:-Rscript}"
macs2="${MACS2:-macs2}"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
extract_barcodes="$src/extract_barcodes.py"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
mtx2svg="$src/position_matrix.pl"
createSeuratObj="$src/createSeuratObj.R"
spatial_metadata="$src/metadata_seurat_spatial.py"
bigWigToBedGraph="${BIGWIG_TO_BEDGRAPH:-bigWigToBedGraph}"
bedGraphToBigWig="${BEDGRAPH_TO_BIGWIG:-bedGraphToBigWig}"
zUMI="${ZUMIS:-bash /path/to/zUMIs.sh}"
## ---- FILES ---
hg38_idx="${HG38_BOWTIE2_INDEX:-/path/to/bowtie2/hg38}"
mm10_idx="${MM10_BOWTIE2_INDEX:-/path/to/bowtie2/mm10}"
chrom_size_var="${species^^}_CHROM_SIZES"
chromSize="${!chrom_size_var}"
hg38_autosome="${HG38_AUTOSOME_BED:-/path/to/hg38.autosome.txt}"
mm10_autosome="${MM10_AUTOSOME_BED:-/path/to/mm10.autosome.txt}"
rmsk_hg38="${HG38_RMSK_BED:-/path/to/hg38.rmsk.bed}"
rmsk_mm10="${MM10_RMSK_BED:-/path/to/mm10.rmsk.bed}"
hg38_bis="${HG38_BISMARK_INDEX:-/path/to/Bismark_hg38}"
mm10_bis="${MM10_BISMARK_INDEX:-/path/to/Bismark_mm10}"
yaml_template="${repo_root}/config/DBiT_multiome_RNA.yaml"
read_len=20

declare -A Ref_bis
Ref_bis["hg38"]=$hg38_bis
Ref_bis["mm10"]=$mm10_bis

declare -A Ref_fa
Ref_fa["hg38"]=$hg38_idx
Ref_fa["mm10"]=$mm10_idx
bowti2_idx=${Ref_fa[$species]}

declare -A effective_size
effective_size["hg38"]=2913022398
effective_size["mm10"]=2652783500
effective_genome_size=${effective_size[$species]}
ref_bis=${Ref_bis[$species]}

if [[ $SLURM_CPUS_PER_TASK -ge 8 ]]; then
    thread_trim=8
else
    thread_trim=$SLURM_CPUS_PER_TASK
fi 

if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
    thread_sort=12
else
    thread_sort=$SLURM_CPUS_PER_TASK
fi 


function trim_fq(){
    read_len=20

    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    ## barcode is on Read1; only trim Read2
    $cutadapt -j $thread_trim \
        -A "A{9};max_error_rate=0.2;min_overlap=5" \
        --minimum-length $read_len \
        --json $outdir/trim/$sampleid.trimming_report.txt \
        -o $outdir/trim/${sampleid}_clean.R1.fastq.gz \
        -p $outdir/trim/${sampleid}_clean.R2.fastq.gz \
        $read1 \
        $read2
}

function run_zUMI(){

    if [[ ! -d $outdir/zUMI_out ]];then 
        mkdir -p $outdir/zUMI_out
    fi 
    out_temp="$outdir/zUMI_out"
    read1_zumi=$outdir/trim/${sampleid}_clean.R1.fastq.gz
    read2_zumi=$outdir/trim/${sampleid}_clean.R2.fastq.gz

    cat $yaml_template |
        sed "s|SAMPLEID|${sampleid}|" |
        sed "s|READ1|${read1_zumi}|" |
        sed "s|READ2|${read2_zumi}|" |
        sed "s|OUT_zUMI|${out_temp}|" > $outdir/zUMI_out/${sampleid}.yaml

    $zUMI -y $outdir/zUMI_out/${sampleid}.yaml
}


function spatial_position(){
    if [[ ! -d $outdir/spatial/${sampleid} ]];then 
        mkdir -p $outdir/spatial/${sampleid}
    fi 
    echo $decode_file

    $python $src/gene_activity.py \
        --input_h5ad $outdir/fragments/${sampleid}_CB.h5ad \
        --species $species \
        --barcode_file $decode_file \
        --outdir $outdir/spatial

    # # detect in tissue barcodes
    perl $mtx2svg $outdir/fragments/${sampleid}_CB.exp.tsv \
        > $outdir/spatial/${sampleid}.raw.svg
    $python $src/svg2png.py \
        -i $outdir/spatial/${sampleid}.raw.svg \
        -o $outdir/spatial/${sampleid}/tissue_lowres_image.png

    $python_cv2 $src/makeMetadata.py \
        --decode_file $decode_file \
        --img_path $outdir/spatial/${sampleid}/tissue_lowres_image.png \
        -o $outdir/spatial/${sampleid}

    # if [[ -s $outdir/fragments/${sampleid}_CB.500.metadata.txt ]];then
    #     mv $outdir/fragments/${sampleid}_CB.500.metadata.txt $outdir/fragments/${sampleid}_CB.metadata.txt
    # fi 
    $Rscript $createSeuratObj \
        $outdir/fragments/${sampleid}_CB.exp.tsv \
        $outdir/fragments/${sampleid}_CB.metadata.txt \
        $outdir/spatial/spatial_barcodes.txt \
        $outdir/spatial/${sampleid}.spatial.rds \
        $outdir/spatial/${sampleid}

}
set -x 
trim_fq

run_zUMI