#!/usr/bin/env bash

# GitHub-ready entrypoint copied from the development workspace.
# Machine-specific tools and references are resolved from config/pipeline.env.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
export SPATIAL_EPIGENOME_REPO_ROOT="${repo_root}"
# shellcheck source=../lib/common.sh
source "${repo_root}/lib/common.sh"
load_pipeline_config "${repo_root}"
SLURM_CPUS_PER_TASK="${SLURM_CPUS_PER_TASK:-$(threads_or_default 4)}"



set -e
set -o pipefail

helpdoc() {
    cat <<EOF
Description:
    [main::] Spatial ATAC-seq based on IVT data of DBiT-seq processing pipeline created by Maoxu Wang, Xie Lab, Peking University.
    Last update: 2024.08.30
Usage:
    $run [options]
    -h print user manual information
Options:
    --read1       -- Read1 (.fastq.gz)
    --read2       -- Read2 (.fastq.gz)
    --sampleid     -- sampleid name specified
    --species      -- e.g. hg38 or mm10
    --decode_file    -- generated by DBiT chip
    --n_line      -- number of lines to process (default: all lines)
    --outdir      -- output directory
    --img        -- fluorescence or HE image
    --option      -- steps to run
    --debug       -- debug mode
    --help       -- print manual
EOF
}
ARGS=$(getopt -o o:i:h -l read1:,read2:,sampleid:,species:,decode_file:,outdir:,img:,option:,debug:,paired:,help -- "$@")



if [ $? != 0 ]; then
    echo "terminating..." >&2
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
        --read1)
            read1=$2
            shift 2
        ;;
        --read2)
            read2=$2
            shift 2
        ;;
        --sampleid)
            sampleid=$2
            shift 2
        ;;
        --species)
            species=$2
            shift 2
        ;;
        --decode_file)
            decode_file=$2
            shift 2
        ;;
        -o | --outdir)
            outdir=$2
            shift 2
        ;;
        --img)
            img=$2
            shift 2
        ;;
        --option)
            option=$2
            shift 2
        ;;
        --debug)
            debug=$2
            shift 2
        ;;
        --paired)
            paired=$2
            shift 2
        ;;
        -h | --help)
            helpdoc
            exit 1
        ;;
        --)
            shift
            echo "Parameters recevied."
            break
        ;;
        *)
            echo "unknown parameter:" $1
            helpdoc
            exit 1
        ;;
    esac
done


if [[ ! -n $outdir ]]; then outdir="./result"; fi
if [[ ! -n $option ]]; then option="pipe"; fi
if [[ ! -n $paired ]]; then paired="FALSE"; fi

if [[ ! -n $decode_file ]]; then
    decode_file="${DBIT_DECODE_FILE:-${repo_root}/resources/DBiT/spatial_barcodes.txt}"
fi

if [[ ! -n $debug ]]; then debug=False; fi

if [[ ! -n $sampleid ]]; then
    echo "Please specify sampleid name"
    exit
fi

if [[ ! -n $species ]]; then
    echo "Please specify species"
    exit
fi


if [[ $SLURM_CPUS_PER_TASK > 12 ]];then
    sort_thread=12
else
    sort_thread=$SLURM_CPUS_PER_TASK
fi


trim_galore="${TRIM_GALORE:-trim_galore}"
cutadapt="${CUTADAPT:-cutadapt}"
bedtools="${BEDTOOLS:-bedtools}"
bowtie2="${BOWTIE2:-bowtie2}"
samtools="${SAMTOOLS:-samtools}"
src="${SPATIAL_EPIGENOME_SCRIPT_DIR:-${repo_root}/scripts}"
umi_tools="${UMI_TOOLS:-umi_tools}"
spatial_IVT="${SPATIAL_IVT:-spatial_IVT}"
seqkit="${SEQKIT:-seqkit}"
python="${PYTHON:-python}"
python_cv2="${PYTHON_CV2:-python}"
merge_super_spot="${MERGE_SUPER_SPOT:-levelMatrix.py}"
picard="${PICARD:-picard}"
Rscript="${RSCRIPT:-Rscript}"
macs2="${MACS2:-macs2}"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
extract_barcodes="$src/DBiT/extract_barcodes.py"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
mtx2svg="$src/DBiT/position_matrix.pl"
createSeuratObj="$src/DBiT/createSeuratObj.R"
spatial_metadata="$src/DBiT/metadata_seurat_spatial.py"
bigWigToBedGraph="${BIGWIG_TO_BEDGRAPH:-bigWigToBedGraph}"
bedGraphToBigWig="${BEDGRAPH_TO_BIGWIG:-bedGraphToBigWig}"
bbduk_dir="${BBMAP_BBDUK:-bbduk.sh}"
BC_process="${src}/RongFan_sp_atac/BC_process.py"
cellranger="${CELLRANGER_ATAC:-cellranger-atac}"
# Set CELLRANGER_ATAC in config/pipeline.env when using cellranger-atac.
picard="${PICARD:-picard}"

hg38_idx_10X="${HG38_CELLRANGER_ARC_REF:-/path/to/refdata-cellranger-arc-GRCh38}"
mm10_idx_10X="${MM10_CELLRANGER_ARC_REF:-/path/to/refdata-cellranger-arc-mm10}"
chrom_size_var="${species^^}_CHROM_SIZES"
chromSize="${!chrom_size_var}"


hg38_autosome="${HG38_AUTOSOME_BED:-/path/to/hg38.autosome.txt}"
mm10_autosome="${MM10_AUTOSOME_BED:-/path/to/mm10.autosome.txt}"
rmsk_hg38="${HG38_RMSK_BED:-/path/to/hg38.rmsk.bed}"
rmsk_mm10="${MM10_RMSK_BED:-/path/to/mm10.rmsk.bed}"

hg38_idx="${HG38_BOWTIE2_INDEX:-/path/to/bowtie2/hg38}"
mm10_idx="${MM10_BOWTIE2_INDEX:-/path/to/bowtie2/mm10}"


read_len=20
declare -A Ref_fa
Ref_fa["hg38"]=$hg38_idx
Ref_fa["mm10"]=$mm10_idx
bowti2_idx=${Ref_fa[$species]}


declare -A Ref_fa_10X
Ref_fa_10X["hg38"]=$hg38_idx_10X
Ref_fa_10X["mm10"]=$mm10_idx_10X
idx_10X=${Ref_fa_10X[$species]}

declare -A effective_size
effective_size["hg38"]=2913022398
effective_size["mm10"]=2652783500
effective_genome_size=${effective_size[$species]}


if [[ $SLURM_CPUS_PER_TASK -ge 8 ]]; then
    thread_trim=8
else
    thread_trim=$SLURM_CPUS_PER_TASK
fi

if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
    thread_sort=12
else
    thread_sort=$SLURM_CPUS_PER_TASK
fi



function filterLinker(){
    if [[ ! -d $outdir/processed_reads ]];then
        mkdir -p $outdir/processed_reads
    fi
    
    if [[ ! -d $outdir/fastq ]];then
        mkdir -p $outdir/fastq
    fi
    
    bash ${bbduk_dir} \
        in1=$read1 \
        in2=$read2 \
        outm1=$outdir/processed_reads/$sampleid.L1.R1.fastq.gz \
        outm2=$outdir/processed_reads/$sampleid.L1.R2.fastq.gz \
        k=34 mm=f rcomp=f restrictleft=85 skipr2=t \
        hdist=3 \
        stats=$outdir/processed_reads/${sampleid}_stats.linker1.txt \
        threads=$SLURM_CPUS_PER_TASK \
        literal=AGATGTGTATAAGAGACAGCATCGGCGTACGACT
    
    bash ${bbduk_dir} \
        in1=$outdir/processed_reads/$sampleid.L1.R1.fastq.gz \
        in2=$outdir/processed_reads/$sampleid.L1.R2.fastq.gz \
        outm1=$outdir/processed_reads/$sampleid.LinkerFiltered.R1.fastq.gz \
        outm2=$outdir/processed_reads/$sampleid.LinkerFiltered.R2.fastq.gz \
        k=30 mm=f rcomp=f restrictleft=43 skipr2=t \
        hdist=3 \
        stats=$outdir/processed_reads/${sampleid}_stats.linker2.txt \
        threads=$SLURM_CPUS_PER_TASK \
        literal=ATCCACGTGCTTGAGAGGCCAGAGCATTCG
    
    $python $BC_process \
        --input $outdir/processed_reads/$sampleid.LinkerFiltered.R1.fastq.gz \
        --output_R1 $outdir/fastq/${sampleid}_S1_L001_R1_001.fastq \
        --output_R2 $outdir/fastq/${sampleid}_S1_L001_R2_001.fastq \
    
    mv $outdir/processed_reads/$sampleid.LinkerFiltered.R2.fastq.gz \
        $outdir/fastq/${sampleid}_S1_L001_R3_001.fastq.gz
    
    
}

function cell_ranger(){
    
    if [ -d "$outdir/$sampleid" ]; then
        echo "Removing existing Cell Ranger output directory: $outdir/$sampleid"
        rm -r "$outdir/$sampleid"
    fi
    
    cd $outdir
    
    $cellranger count \
        --id=${sampleid} \
        --reference=$idx_10X \
        --fastqs=$outdir/fastq \
        --sample=${sampleid} \
        --localcores=$SLURM_CPUS_PER_TASK \
        --localmem=64 
    cd -
}


function trim_Nextera(){
    if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
        thread_trim=12
    else
        thread_trim=$SLURM_CPUS_PER_TASK
    fi
    
    if [[ ! -d $outdir/trim ]];then
        mkdir -p $outdir/trim
    fi
    
    if [[ ! -d $outdir/align ]];then
        mkdir -p $outdir/align
    fi
    
    
    ## CB:UMI:readname
    echo $sampleid
    $bowtie2 -x $bowti2_idx \
    --no-unal \
    -X 2000 \
    -1 $outdir/trim/${sampleid}.R1_val_1.fq.gz \
    -2 $outdir/trim/${sampleid}.R2_val_2.fq.gz \
    -p $SLURM_CPUS_PER_TASK \
    | $samtools sort -@ $thread_sort -m "12G" \
    > $outdir/align/${sampleid}.sorted.bam
    
    $samtools index $outdir/align/${sampleid}.sorted.bam
    $samtools stats $outdir/align/${sampleid}.sorted.bam > $outdir/align/${sampleid}.bam.stat
    
}

function bulk(){
    ### calculate as bulk samples
    if [[ ! -d $outdir/bulk ]];then
        mkdir -p $outdir/bulk
    fi
    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.rmdup.bam
    
    ## filter the chrM reads
    $samtools idxstats -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.rmdup.bam \
    | cut -f 1 | grep -v MT \
    | xargs $samtools view -b $outdir/bulk/${sampleid}.rmdup.bam > $outdir/bulk/${sampleid}.clean.bam
    
    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.clean.bam
    
    effect_genome_size=2652783500
    
    $bamCoverage --numberOfProcessors $SLURM_CPUS_PER_TASK \
    --binSize 10 \
    --normalizeUsing RPGC \
    --effectiveGenomeSize $effective_genome_size \
    --bam $outdir/bulk/${sampleid}.clean.bam \
    -o $outdir/bulk/${sampleid}.clean.bw
    
    
    
}

# Generate Cell Ranger-compatible FASTQs before running Cell Ranger ATAC.
set -x

echo "[$(date)] Filter linkers..."
filterLinker

echo "[$(date)] Cell Ranger ATAC..."
cell_ranger
