#!/usr/bin/env bash

# GitHub-ready entrypoint copied from the development workspace.
# Machine-specific tools and references are resolved from config/pipeline.env.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
export SPATIAL_EPIGENOME_REPO_ROOT="${repo_root}"
# shellcheck source=../lib/common.sh
source "${repo_root}/lib/common.sh"
load_pipeline_config "${repo_root}"
SLURM_CPUS_PER_TASK="${SLURM_CPUS_PER_TASK:-$(threads_or_default 4)}"


set -e
set -o pipefail

helpdoc() {
    cat <<EOF
Description:
    [main::] Spatial ATAC-seq based on IVT data of DBiT platform processing pipeline created by Maoxu Wang, Xie Lab, Peking University.
    Last update: 2025.03.30
Usage:
    $run [options]
        -h print user manual information
Options:
    --read1             -- Read1 (.fastq.gz)
    --read2             -- Read2 (.fastq.gz)
    --sampleid          -- sampleid name specified 
    --species           -- e.g. hg38 or mm10
    --decode_file       -- generated by DBiT chip
    --n_line            -- number of lines to process (default: all lines)
    --outdir            -- output directory
    --img               -- fluorescence or HE image
    --option            -- steps to run
    --debug             -- debug mode
    --help              -- print manual
EOF
}
ARGS=$(getopt -o o:i:h -l read1:,read2:,sampleid:,species:,decode_file:,n_line:,outdir:,img:,option:,debug:,paired:,mode:,in_tissue:,help -- "$@")



if [ $? != 0 ]; then
    echo "terminating..." >&2
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
    --read1)
        read1=$2
        shift 2
        ;;
    --read2)
        read2=$2
        shift 2
        ;; 
    --sampleid)
        sampleid=$2
        shift 2
        ;; 
    --species)
        species=$2
        shift 2
        ;; 
    --decode_file)
        decode_file=$2
        shift 2
        ;;  
    --n_line)
        n_line=$2
        shift 2
        ;;
    -o | --outdir)
        outdir=$2
        shift 2
        ;;
    --img)
        img=$2
        shift 2
        ;;
    --option)
        option=$2
        shift 2
        ;;
    --debug)
        debug=$2
        shift 2
        ;;
    --paired)
        paired=$2
        shift 2
        ;;
    --mode)
        mode=$2
        shift 2
        ;;
    --in_tissue)
        in_tissue=$2
        shift 2
        ;;
    -h | --help)
        helpdoc
        exit 1
        ;;
    --)
        shift
        echo "Parameters recevied."
        break
        ;;
    *)
        echo "unknown parameter:" $1
        helpdoc
        exit 1
        ;;
    esac
done

if [[ ! $read1 =~ "R1" ]]; then
    echo $read1 "wrong Read1 specified"
    exit
fi

if [[ ! $read2 =~ "R2" ]]; then
    echo $read2 "wrong Read2 specified"
    exit
fi

if [[ ! -n $outdir ]]; then outdir="./result"; fi
if [[ ! -n $in_tissue ]]; then in_tissue="TRUE"; fi

if [[ ! -n $n_line ]]; then n_line="-1"; fi
if [[ ! -n $option ]]; then option="pipe"; fi
if [[ ! -n $paired ]]; then paired="FALSE"; fi
if [[ ! -n $mode ]]; then mode="atac"; fi

if [[ ! -n $decode_file ]]; then 
    decode_file="${DBIT_DECODE_FILE:-${repo_root}/resources/DBiT/spatial_barcodes.txt}"
fi

if [[ ! -n $debug ]]; then debug=False; fi

if [[ ! -n $sampleid ]]; then
    echo "Please specify sampleid name"
    exit
fi

if [[ ! -n $species ]]; then
    echo "Please specify species"
    exit
fi

if [[ $SLURM_CPUS_PER_TASK > 12 ]];then 
    sort_thread=12
else
    sort_thread=$SLURM_CPUS_PER_TASK
fi 


trim_galore="${TRIM_GALORE:-trim_galore}"
cutadapt="${CUTADAPT:-cutadapt}"
bedtools="${BEDTOOLS:-bedtools}"
bowtie2="${BOWTIE2:-bowtie2}"
samtools="${SAMTOOLS:-samtools}"
src="${SPATIAL_EPIGENOME_SCRIPT_DIR:-${repo_root}/scripts}"
umi_tools="${UMI_TOOLS:-umi_tools}"
spatial_IVT="${SPATIAL_IVT:-spatial_IVT}"
seqkit="${SEQKIT:-seqkit}"
python="${PYTHON:-python}"
python_cv2="${PYTHON_CV2:-python}"
merge_super_spot="${MERGE_SUPER_SPOT:-levelMatrix.py}"
picard="${PICARD:-picard}"
Rscript="${RSCRIPT:-Rscript}"
macs2="${MACS2:-macs2}"
extract_barcodes="$src/DBiT/extract_barcodes.py"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
mtx2svg="$src/DBiT/position_matrix.py"
createSeuratObj="$src/DBiT/createSeuratObj.R"
signac_chromVar="$src/DBiT//signac_chromVar.R"
spatial_metadata="$src/DBiT/metadata_seurat_spatial.py"
bigWigToBedGraph="${BIGWIG_TO_BEDGRAPH:-bigWigToBedGraph}"
bedGraphToBigWig="${BEDGRAPH_TO_BIGWIG:-bedGraphToBigWig}"
picard="${PICARD:-picard}"

hg38_idx="${HG38_BOWTIE2_INDEX:-/path/to/bowtie2/hg38}"
mm10_idx="${MM10_BOWTIE2_INDEX:-/path/to/bowtie2/mm10}"
chrom_size_var="${species^^}_CHROM_SIZES"
chromSize="${!chrom_size_var}"

hg38_autosome="${HG38_AUTOSOME_BED:-/path/to/hg38.autosome.txt}"
mm10_autosome="${MM10_AUTOSOME_BED:-/path/to/mm10.autosome.txt}"
rmsk_hg38="${HG38_RMSK_BED:-/path/to/hg38.rmsk.bed}"
rmsk_mm10="${MM10_RMSK_BED:-/path/to/mm10.rmsk.bed}"

read_len=20

declare -A Ref_fa
Ref_fa["hg38"]=$hg38_idx
Ref_fa["mm10"]=$mm10_idx
bowti2_idx=${Ref_fa[$species]}

declare -A effective_size
effective_size["hg38"]=2913022398
effective_size["mm10"]=2652783500
effective_genome_size=${effective_size[$species]}

declare -A MACS2_GENOME=(
  [hg38]="hs"
  [mm10]="mm"
)

if [[ $SLURM_CPUS_PER_TASK -ge 8 ]]; then
    thread_trim=8
else
    thread_trim=$SLURM_CPUS_PER_TASK
fi 

if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
    thread_sort=12
else
    thread_sort=$SLURM_CPUS_PER_TASK
fi 


function stat_abortive(){
    
    if [[ ! -d $outdir/stat_abortive ]];then 
        mkdir -p $outdir/stat_abortive
    fi 
    thread_trim=8

    head -n 400000 <(zcat $read1) | pigz > $outdir/stat_abortive/$sampleid.100K.R1.fastq.gz

    echo "Downsampling to 100K reads..."

    $cutadapt -j $thread_trim \
        -a "A{9};max_error_rate=0.2;min_overlap=3" \
        --trim-n \
        --no-indels \
        --json $outdir/stat_abortive/$sampleid.trimming_report.txt \
        -e 2 \
        -o $outdir/stat_abortive/${sampleid}_polyA_trimmed.R1.fastq.gz \
        $outdir/stat_abortive/$sampleid.100K.R1.fastq.gz

    $seqkit fx2tab $outdir/stat_abortive/${sampleid}_polyA_trimmed.R1.fastq.gz \
        -l -i -Q -n > $outdir/stat_abortive/$sampleid.len.stat.txt
    awk '{print $2}' $outdir/stat_abortive/$sampleid.len.stat.txt > $outdir/stat_abortive/$sampleid.len.stat.tmp
    mv $outdir/stat_abortive/$sampleid.len.stat.tmp $outdir/stat_abortive/$sampleid.len.stat.txt

    $Rscript $src/plot_abortive_distribution.R $outdir/stat_abortive/$sampleid.len.stat.txt $outdir/stat_abortive/$sampleid

}


function barcode_calling(){
    if [[ ! -d $outdir/barcode ]];then 
        mkdir -p $outdir/barcode
    fi 

    if [ ! -s $read1 ]; then
        echo $read1 "Read1 not exist"
        exit
    fi

    if [ ! -s $read2 ]; then
        echo $read2 "Read2 not exist"
        exit
    fi


    if [[ $n_line -eq "-1" ]];then 
        if [[ -s $outdir/barcode/${sampleid}.total_readsN.txt ]];then
            n_line=$(head -n 1 $outdir/barcode/${sampleid}.total_readsN.txt | awk '{print $1 * 4}' | xargs) 
            echo "$n_line is processing..."
        else
            echo "All lines is processing..."
        fi
    fi

    if [[ $paired == "TRUE" ]];then
        $python_cv2 $extract_barcodes \
            --read1 $read1 \
            --read2 $read2 \
            -o $outdir/barcode \
            --n_lines $n_line \
            --sampleName $sampleid \
            --paired \
            --threads $SLURM_CPUS_PER_TASK
    else
        $python_cv2 $extract_barcodes \
            --read1 $read1 \
            --read2 $read2 \
            -o $outdir/barcode \
            --n_lines $n_line \
            --sampleName $sampleid \
            --threads $SLURM_CPUS_PER_TASK \
            --umi_array "(98, 108)" \
            --cb_array "(22, 30)" "(60, 68)"
    fi 

}

function trim_fq(){
    if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
        thread_trim=12
    else
        thread_trim=$SLURM_CPUS_PER_TASK
    fi 

    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    if [[ ! -s $outdir/trim/${sampleid}_clean.R2.fastq.gz ]];then 

        if [[ $paired == "TRUE" ]];then
            $cutadapt -j $thread_trim \
                --poly-a \
                -a "A{9};max_error_rate=0.2;min_overlap=3" \
                -a "CTGTCTCTTATACACATCT" \
                -A "CTGTCTCTTATACACATCT" \
                --trim-n \
                --minimum-length $read_len \
                --json $outdir/trim/$sampleid.trimming_report.txt \
                -o $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
                -p $outdir/trim/${sampleid}_clean_barcoded.R2.fastq.gz \
                $outdir/barcode/${sampleid}.R1.barcoded.fastq.gz \
                $outdir/barcode/${sampleid}.R2.barcoded.fastq.gz
        else
            $cutadapt -j $thread_trim \
                -q 20 \
                -a "A{9};max_error_rate=0.2;min_overlap=3" \
                --trim-n \
                --no-indels \
                --minimum-length $read_len \
                --json $outdir/trim/$sampleid.trimming_report.txt \
                -e 2 \
                -o $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
                $outdir/barcode/${sampleid}.R1.barcoded.fastq.gz
        fi 
    else
        echo "sequence is trimmed already."
    fi 
}

function trim_Nextera(){
    if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
        thread_trim=12
    else
        thread_trim=$SLURM_CPUS_PER_TASK
    fi 

    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    if [[ ! -s $outdir/trim/${sampleid}_clean.R2.fastq.gz ]];then 
        $trim_galore \
            --paired \
            --nextera \
            --stringency 5 \
            --cores $thread_trim \
            -o $outdir/trim \
            $outdir/barcode/${sampleid}.R1.barcoded.fastq.gz \
            $outdir/barcode/${sampleid}.R2.barcoded.fastq.gz
    else
        echo "sequence is trimmed already."
    fi 

    ## CB:UMI:readname
    $bowtie2 -x $bowti2_idx \
        --no-unal \
        -X 2000 \
        -1 $outdir/trim/${sampleid}.R1_val_1.fq.gz \
        -2 $outdir/trim/${sampleid}.R2_val_2.fq.gz \
        -p $SLURM_CPUS_PER_TASK \
        | awk -v OFS='\t' '$0~/^@/ { print; next } { split($1,bc,":"); total=length(bc); print $0 "\tCB:Z:" bc[1] "\tUB:Z:" bc[2]}' \
        | $samtools sort -@ $thread_sort -m "12G" \
        | $samtools view -q 30 -b \
        > $outdir/align/${sampleid}.sorted.bam

    $samtools index $outdir/align/${sampleid}.sorted.bam
    $samtools stats $outdir/align/${sampleid}.sorted.bam > $outdir/align/${sampleid}.bam.stat

}


function align(){

    if [[ ! -d $outdir/align ]];then 
        mkdir -p $outdir/align
    fi 

    if [[ $paired == "TRUE" ]];then
        $bowtie2 -x $bowti2_idx \
            --no-unal \
            -X 2000 \
            -1 $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
            -2 $outdir/trim/${sampleid}_clean_barcoded.R2.fastq.gz \
            -p $SLURM_CPUS_PER_TASK \
            | awk -v OFS='\t' '$0~/^@/ { print; next } { split($1,bc,":"); total=length(bc); print $0 "\tCB:Z:" bc[1] "\tUB:Z:" bc[2]}' \
            | $samtools sort -@ $thread_sort -m "12G" \
            | $samtools view -q 30 -b \
            > $outdir/align/${sampleid}.sorted.bam
    else
        $bowtie2 -x $bowti2_idx \
            -U $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
            --no-unal \
            -p $SLURM_CPUS_PER_TASK \
            | awk -v OFS='\t' '$0~/^@/ { print; next } { split($1,bc,":"); total=length(bc); print $0 "\tCB:Z:" bc[1] "\tUB:Z:" bc[2]}' \
            | $samtools sort -@ $thread_sort -m "12G" \
            | $samtools view -q 20 -b \
            > $outdir/align/${sampleid}.sorted.bam
    fi 

    $samtools index $outdir/align/${sampleid}.sorted.bam
    $samtools stats $outdir/align/${sampleid}.sorted.bam > $outdir/align/${sampleid}.bam.stat

}


function detect_region_of_interest(){
    if [[ ! -d $outdir/spatial/${sampleid} ]];then 
        mkdir -p $outdir/spatial/${sampleid}
    fi 

    if [[ ! -d $outdir/fragments ]];then 
        mkdir -p $outdir/fragments
    fi 
    echo $decode_file

    if [[ ! -s $outdir/fragments/${sampleid}_CB.exp.tsv ]];then
        $python $src/gene_activity.py \
            --input_h5ad $outdir/align/${sampleid}.sorted.bam \
            --species $species \
            --barcode_file $decode_file \
            --outdir $outdir/spatial \
            --output_prefix $outdir/fragments/${sampleid}_CB
        
        #     > $outdir/spatial/${sampleid}.raw.svg

        $python $mtx2svg $outdir/fragments/${sampleid}_CB.exp.tsv \
            > $outdir/spatial/${sampleid}.raw.svg
    fi 
    $python $mtx2svg $outdir/fragments/${sampleid}_CB.exp.tsv \
        > $outdir/spatial/${sampleid}.raw.svg
    if [[ $in_tissue == "TRUE" ]];then 
        $python_cv2 $src/makeMetadata.py \
            --decode_file $decode_file \
            --svg_path $outdir/spatial/${sampleid}.raw.svg \
            -o $outdir/spatial/${sampleid} \
            --in_tissue
    else
        $python_cv2 $src/makeMetadata.py \
            --decode_file $decode_file \
            --svg_path $outdir/spatial/${sampleid}.raw.svg \
            -o $outdir/spatial/${sampleid}
    fi
}

function snapATAC2(){
    if [[ ! -d $outdir/fragments ]];then 
        mkdir -p $outdir/fragments
    fi 
    
    if [[ $paired == "TRUE" ]];then
        $python $src/DBiT/snapatac2_preprocess.py \
            --input_bam $outdir/align/${sampleid}.sorted.bam \
            --output_dir $outdir/fragments \
            --sampleid $sampleid \
            --species $species \
            --max_iter 1 \
            --is_paired \
            --n_features 50000 \
            --tissue_barcode $outdir/spatial/${sampleid}/ROI_barcodes.txt
    else
        $python $src/DBiT/snapatac2_preprocess.py \
            --input_bam $outdir/align/${sampleid}.sorted.bam \
            --output_dir $outdir/fragments \
            --sampleid $sampleid \
            --species $species \
            --max_iter 1 \
            --n_features 50000 \
            --tissue_barcode $outdir/spatial/${sampleid}/ROI_barcodes.txt
    fi
    pigz -d $outdir/fragments/${sampleid}_CB.fragments.tsv.gz 
    sort -k1,1V -k2,2n \
        -T . $outdir/fragments/${sampleid}_CB.fragments.tsv | awk '{print $1, $2, $3, $4, $5}' OFS="\t" > $outdir/fragments/${sampleid}.fragments.tsv
    bgzip $outdir/fragments/${sampleid}.fragments.tsv

    tabix -p bed $outdir/fragments/${sampleid}.fragments.tsv.gz
    pigz $outdir/fragments/${sampleid}_CB.fragments.tsv

    $Rscript $signac_chromVar \
        $outdir/fragments/${sampleid}.peak_matrix.h5 \
        $outdir/fragments/${sampleid}.fragments.tsv.gz \
        $species



    ls $outdir/fragments/*metadata.txt | while read meta_file;do 
        prefix_sample=$(basename -s ".metadata.txt" $meta_file)
        $Rscript $src/atac_QC.R 10000 $meta_file $outdir/fragments/$prefix_sample.qc.pdf
    done 

}


function spatial_position(){
    if [[ ! -d $outdir/spatial/${sampleid} ]];then 
        mkdir -p $outdir/spatial/${sampleid}
    fi

    $Rscript $createSeuratObj \
        --count_matrix_path $outdir/fragments/${sampleid}_CB.exp.tsv \
        --metadata_file $outdir/fragments/${sampleid}_CB.metadata.txt \
        --spatial_barcode_file $outdir/spatial/spatial_barcodes.txt \
        --out_seurat $outdir/spatial/${sampleid}.spatial.rds \
        --image_dir $outdir/spatial/${sampleid} \
        --in_tissue TRUE
}


function pseudo_bulk(){
    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    $cutadapt -j $thread_trim \
        -q 20 \
        -a "A{9};max_error_rate=0.2;min_overlap=3" \
        --trim-n \
        --no-indels \
        --minimum-length $read_len \
        --json $outdir/trim/$sampleid.trimming_report.txt \
        -e 2 \
        -o $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
        $read1

    if [[ ! -d $outdir/align ]];then 
        mkdir -p $outdir/align
    fi 

    $bowtie2 -x $bowti2_idx \
        -U $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
        --no-unal \
        -p $SLURM_CPUS_PER_TASK \
        | $samtools sort -@ $thread_sort -m "12G" \
        | $samtools view -q 30 -b \
        > $outdir/align/${sampleid}.sorted.bam
    
    if [[ ! -d $outdir/bulk ]];then 
        mkdir -p $outdir/bulk
    fi 
    $picard MarkDuplicates \
        -I $outdir/align/${sampleid}.sorted.bam \
        -O $outdir/bulk/${sampleid}.rmdup.bam \
        -M $outdir/bulk/${sampleid}.dedup.txt \
        -REMOVE_DUPLICATES true \
        -READ_NAME_REGEX null \
        --TMP_DIR ${outdir}/bulk
    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.rmdup.bam

    # Remove chrM alignments before bulk coverage and peak calling.
    $samtools idxstats -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.rmdup.bam \
        | cut -f 1 | grep -v MT \
        | xargs $samtools view -b $outdir/bulk/${sampleid}.rmdup.bam > $outdir/bulk/${sampleid}.temp.bam
    


    # Keep high-confidence alignments for bulk coverage and peak calling.
    $samtools view -bh -q 30 -@ $SLURM_CPUS_PER_TASK \
        -o $outdir/bulk/${sampleid}.clean.bam \
        $outdir/bulk/${sampleid}.temp.bam

    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.clean.bam

    
    $bamCoverage --numberOfProcessors $SLURM_CPUS_PER_TASK \
        --binSize 10 \
        --normalizeUsing RPGC \
        --effectiveGenomeSize $effective_genome_size \
        --bam $outdir/bulk/${sampleid}.clean.bam \
        -o $outdir/bulk/${sampleid}.clean.bw

    $macs2 callpeak \
        -f BAM \
        -g ${MACS2_GENOME[$species]} \
        --nomodel --shift -100 --extsize 200 \
        --keep-dup all --qvalue 0.01 \
        -t $outdir/bulk/${sampleid}.clean.bam \
        -n $sampleid \
        --outdir $outdir/bulk

}


function bulk(){
    ### calculate as bulk samples
    if [[ ! -d $outdir/bulk ]];then 
        mkdir -p $outdir/bulk
    fi 
    $picard MarkDuplicates \
        -I $outdir/align/${sampleid}.sorted.bam \
        -O $outdir/bulk/${sampleid}.rmdup.bam \
        -M $outdir/bulk/${sampleid}.dedup.txt \
        -REMOVE_DUPLICATES true \
        -READ_NAME_REGEX null \
        --TMP_DIR ${outdir}/bulk
    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.rmdup.bam

    # Remove chrM alignments before bulk coverage and peak calling.
    $samtools idxstats -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.rmdup.bam \
        | cut -f 1 | grep -v MT \
        | xargs $samtools view -b $outdir/bulk/${sampleid}.rmdup.bam > $outdir/bulk/${sampleid}.temp.bam
    


    # Keep high-confidence alignments for bulk coverage and peak calling.
    $samtools view -bh -q 30 -@ $SLURM_CPUS_PER_TASK \
        -o $outdir/bulk/${sampleid}.clean.bam \
        $outdir/bulk/${sampleid}.temp.bam

    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.clean.bam

    
    $bamCoverage --numberOfProcessors $SLURM_CPUS_PER_TASK \
        --binSize 10 \
        --normalizeUsing RPGC \
        --effectiveGenomeSize $effective_genome_size \
        --bam $outdir/bulk/${sampleid}.clean.bam \
        -o $outdir/bulk/${sampleid}.clean.bw

    $macs2 callpeak \
        -f BAM \
        -g ${MACS2_GENOME[$species]} \
        --nomodel --shift -100 --extsize 200 \
        --keep-dup all --qvalue 0.01 \
        -t $outdir/bulk/${sampleid}.clean.bam \
        -n $sampleid \
        --outdir $outdir/bulk


}

function stat(){

    if [[ ! -d $outdir/stat ]];then 
        mkdir -p $outdir/stat 
    fi 
    
        
    bam="$outdir/bulk/${sampleid}.clean.bam"
    peaks="$outdir/bulk/${sampleid}_peaks.narrowPeak"

    # check file
    if [ ! -s $bam ]; then
        echo $bam " not exist"
        exit
    fi

    if [ ! -s $peaks ]; then
        echo $peaks "Read2 not exist"
        exit
    fi

    echo "→ Computing FRiP for $sampleid …"

    # 1) total reads
    total_reads=$(samtools view -c -@ 12 "$bam")

    # 2) reads in peaks
    reads_in_peaks=$( \
        $bedtools sort -i "$peaks" \
        | $bedtools merge -i stdin \
        | $bedtools intersect -u -nonamecheck \
            -a "$bam" \
            -b stdin -ubam \
        | samtools view -c \
    )

    # 3) 计算 FRiP（保留四位小数）
    frip=$(awk 'BEGIN{printf "%.4f", '$reads_in_peaks'/'$total_reads'}')

    # 写入结果
    if [[ ! -s ${outdir}/stat/stat.txt ]]; then
        echo -e "SampleID\tSpecies\t" \
            "Total_reads\tBarcode_valid_percent\t" \
            "Reads_high_qualtity_percent\t" \
            "Unique_aligned_reads\t" \
            "Unique_align_rate\t" \
            "median_dup\t" \
            "median_n_fragments\t" \
            "reads_in_peaks\t" \
            "frip" > ${outdir}/stat/stat.txt
    fi    
    valid_barcode_reads=$(less $outdir/QC/${sampleid}.mapped.tsv.gz | awk '{sum+=$2}END{print sum}')
    total_raw_reads=$(less $outdir/barcode/${sampleid}.total_readsN.txt  | xargs)
    valid_barcode_percent=$(echo "scale=4; $valid_barcode_reads / $total_raw_reads * 100" | bc | xargs)
    reads_passing_filter=$(grep 'output":' $outdir/trim/${sampleid}.trimming_report.txt | awk '{print $2}' | head -n 1 | sed 's/,//g')
    reads_passing_filter_rate=$(echo "scale=2; $reads_passing_filter / $valid_barcode_reads * 100" | bc | xargs)
    
    unique_align_reads=$($samtools view -q 20 -c -@ 12 $outdir/align/${sampleid}.sorted.bam | xargs)

    align_rate=$(echo "scale=2; $unique_align_reads / $reads_passing_filter * 100" | bc | xargs)

    total_line=$(less $outdir/fragments/${sampleid}_CB.metadata.txt | wc -l)
    median_n_line=$(echo "scale=0; $total_line / 2" | bc | xargs)
    median_n_frag=$(sort -k2,2n $outdir/fragments/${sampleid}_CB.metadata.txt | head -n $median_n_line | awk '{print $2}' | tail -n 1 | xargs)
    median_dup=$(sort -k3,3n $outdir/fragments/${sampleid}_CB.metadata.txt | head -n $median_n_line | tail -n 1 | awk '{printf "%.2f", $3 * 100}' | xargs)



    echo -e "$sampleid\t${species}\t" \
        "${total_raw_reads}\t" \
        "${valid_barcode_percent}%\t" \
        "${reads_passing_filter_rate}%\t" \
        "${unique_align_reads}\t" \
        "${align_rate}%\t" \
        "${median_dup}\t" \
        "${median_n_frag}\t" \
        "${reads_in_peaks}\t" \
        "${frip}" >> ${outdir}/stat/stat.txt
}


set -x 


case "$option" in
pipe)
    stat_abortive
    barcode_calling
    trim_fq
    align 
    detect_region_of_interest
    snapATAC2
    spatial_position
    bulk
    stat
    ;;
align)
    align
    ;;
QC)
    stat_abortive
    ;;
atac)
    align
    snapATAC2
    spatial_position
    bulk
    stat
    ;;
dedup)
    dedup
    ;;
bulk)
    pseudo_bulk
    ;;
stat)
    stat
    ;;
dedup_UMI)
    dedup_UMI
    ;;
spatial)
    spatial_position
    ;;
no_IVT)
    paired=FALSE
    barcode_calling
    trim_Nextera
    paired=TRUE
    snapATAC2
    bulk
    spatial_position
    ;;
*)
    echo "unknown parameter:" $1
    helpdoc
    exit 1
    ;;
esac
