#!/usr/bin/env bash

# GitHub-ready entrypoint copied from the development workspace.
# Machine-specific tools and references are resolved from config/pipeline.env.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
export SPATIAL_EPIGENOME_REPO_ROOT="${repo_root}"
# shellcheck source=../lib/common.sh
source "${repo_root}/lib/common.sh"
load_pipeline_config "${repo_root}"
SLURM_CPUS_PER_TASK="${SLURM_CPUS_PER_TASK:-$(threads_or_default 4)}"



set -e
set -o pipefail

helpdoc() {
    cat <<EOF
Description:
    [main::] Spatial epigenomics data processing pipeline created by Maoxu Wang, Xie Lab, Peking University.
    Last update: 2024.03.19
Usage:
    $run [options]
        -h print user manual information
Options:
    --read1             -- Read1 (.fastq.gz)
    --read2             -- Read2 (.fastq.gz)
    --sampleid          -- sampleid name specified 
    --species           -- e.g. hg38 or mm10
    --decode_file       -- generated by BMK chip
    --n_line            -- number of lines to process (default: all lines)
    --outdir            -- output directory
    --img               -- fluorescence or HE image
    --option            -- steps to run
    --debug             -- debug mode
    --help              -- print manual
EOF
}
ARGS=$(getopt -o o:i:h -l read1:,read2:,sampleid:,species:,decode_file:,n_line:,outdir:,img:,chanel:,option:,debug:,method:,help -- "$@")



if [ $? != 0 ]; then
    echo "terminating..." >&2
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
    --read1)
        read1=$2
        shift 2
        ;;
    --read2)
        read2=$2
        shift 2
        ;; 
    --sampleid)
        sampleid=$2
        shift 2
        ;; 
    --species)
        species=$2
        shift 2
        ;; 
    --decode_file)
        decode_file=$2
        shift 2
        ;;  
    --n_line)
        n_line=$2
        shift 2
        ;;
    -o | --outdir)
        outdir=$2
        shift 2
        ;;
    --img)
        img=$2
        shift 2
        ;;
    --chanel)
        chanel=$2
        shift 2
        ;;
    --option)
        option=$2
        shift 2
        ;;
    --debug)
        debug=$2
        shift 2
        ;;
    --method)
        method=$2
        shift 2
        ;;
    -h | --help)
        helpdoc
        exit 1
        ;;
    --)
        shift
        echo "Parameters recevied."
        break
        ;;
    *)
        echo "unknown parameter:" $1
        helpdoc
        exit 1
        ;;
    esac
done

## ---- inspect arguments ---
if [[ ! $read1 =~ "R1" ]]; then
    echo $read1 "wrong Read1 specified"
    exit
fi

if [[ ! $read2 =~ "R2" ]]; then
    echo $read2 "wrong Read2 specified"
    exit
fi

if [[ ! -n $outdir ]]; then outdir="./result"; fi
if [[ ! -n $method ]]; then method="S1000"; fi
echo "Method used: $method"

if [[ ! -n $n_line ]]; then n_line="-1"; fi
if [[ ! -n $option ]]; then option="pipe"; fi
if [[ ! -n $chanel ]]; then chanel=2; fi

if [[ ! -n $debug ]]; then debug=False; fi

if [[ ! -n $sampleid ]]; then
    echo "Please specify sampleid name"
    exit
fi

if [[ ! -n $species ]]; then
    echo "Please specify species"
    exit
fi

if [ ! -s $read1 ]; then
    echo $read1 "Read1 not exist"
    exit
fi

if [ ! -s $read2 ]; then
    echo $read2 "Read2 not exist"
    exit
fi

if [[ $SLURM_CPUS_PER_TASK > 12 ]];then 
    sort_thread=12
else
    sort_thread=$SLURM_CPUS_PER_TASK
fi 


## ---- SOFTWARE --- 
cutadapt="${CUTADAPT:-cutadapt}"
bedtools="${BEDTOOLS:-bedtools}"
bowtie2="${BOWTIE2:-bowtie2}"
samtools="${SAMTOOLS:-samtools}"
src="${SPATIAL_EPIGENOME_SCRIPT_DIR:-${repo_root}/scripts}"
umi_tools="${UMI_TOOLS:-umi_tools}"
spatial_IVT="${SPATIAL_IVT:-spatial_IVT}"
seqkit="${SEQKIT:-seqkit}"
python="${PYTHON:-python}"
python_cv2="${PYTHON_CV2:-python}"
merge_super_spot="${MERGE_SUPER_SPOT:-levelMatrix.py}"

picard="${PICARD:-picard}"
Rscript="${RSCRIPT:-Rscript}"
macs2="${MACS2:-macs2}"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
makeSpatialObj="${src}/createSeuratObj.R"
## ---- FILES ---
hg38_idx="${HG38_BOWTIE2_INDEX:-/path/to/bowtie2/hg38}"
mm10_idx="${MM10_BOWTIE2_INDEX:-/path/to/bowtie2/mm10}"

hg38_autosome="${HG38_AUTOSOME_BED:-/path/to/hg38.autosome.txt}"
mm10_autosome="${MM10_AUTOSOME_BED:-/path/to/mm10.autosome.txt}"
rmsk_hg38="${HG38_RMSK_BED:-/path/to/hg38.rmsk.bed}"
rmsk_mm10="${MM10_RMSK_BED:-/path/to/mm10.rmsk.bed}"

read_len=20

declare -A dir_software
BST_src_2_3="${BST_SRC_S1000:-/path/to/BSTMatrix_v2.3.r}"
BST_src_2_4="${BST_SRC_S3000:-/path/to/BSTMatrix_v2.4_adapted}"
dir_software["S1000"]=$BST_src_2_3
dir_software["S3000"]=$BST_src_2_4
BST_src=${dir_software[$method]}

he_detect="${BST_src}/BSTools/RoiLevelMatrix.py"
segCell="${BST_src}/cell_split/SegtoBarcode.py"

segCell="${BST_src}/cellSplit_WMX"

segCell="${BST_src}/cellSplit_WMX"
segCell="${BST_src}/CellSplit"

search="${BST_src}/BSTools/HERegionSearch.py"


declare -A Ref_fa
Ref_fa["hg38"]=$hg38_idx
Ref_fa["mm10"]=$mm10_idx
bowti2_idx=${Ref_fa[$species]}

declare -A effective_size
effective_size["hg38"]=2913022398
effective_size["mm10"]=2652783500
effective_genome_size=${effective_size[$species]}


if [[ $SLURM_CPUS_PER_TASK -ge 8 ]]; then
    thread_trim=8
else
    thread_trim=$SLURM_CPUS_PER_TASK
fi 

if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
    thread_sort=12
else
    thread_sort=$SLURM_CPUS_PER_TASK
fi 

function select_Tn5_reads(){
    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 
    
    ## Select by R2
    $cutadapt -j $thread_trim \
        -G "^AAGCAGTGGTATCAACGCAGAGTACATAGATGTGTATAAGAGACAG" \
        -e 3 \
        -o $outdir/trim/${sampleid}_IVT_R1.fastq.gz \
        -p $outdir/trim/${sampleid}_IVT_R2.fastq.gz \
        --untrimmed-output $outdir/trim/${sampleid}_RNA_R1.fastq.gz \
        --untrimmed-paired-output $outdir/trim/${sampleid}_RNA_R2.fastq.gz \
        $read1 $read2
    
}  

function trim_ME(){
    ## When compared ME reads vs. non-ME reads
    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 
    if [[ ! -s $outdir/trim/${sampleid}_ME_R1.fastq.gz ]];then 
        $cutadapt \
            -j $thread_trim \
            -G "^NAGATGTGTATAAGAGACAG" \
            -G "^NNAGATGTGTATAAGAGACAG" \
            -G "^NNNAGATGTGTATAAGAGACAG" \
            -G "^NNNNAGATGTGTATAAGAGACAG" \
            --no-indels -e 2 \
            -o $outdir/trim/${sampleid}_ME_R1.fastq.gz \
            -p $outdir/trim/${sampleid}_ME_R2.fastq.gz \
            --untrimmed-output $outdir/trim/${sampleid}_woME_R1.fastq.gz \
            --untrimmed-paired-output $outdir/trim/${sampleid}_woME_R2.fastq.gz \
            $read1 $read2
    else
        echo "ME sequence is trimmed already."
    fi 
}


function stat_abortive(){
    
    if [[ ! -d $outdir/stat_abortive ]];then 
        mkdir -p $outdir/stat_abortive
    fi 
    thread_trim=8

    read1=$outdir/trim/${sampleid}_IVT_R1.fastq.gz
    read2=$outdir/trim/${sampleid}_IVT_R2.fastq.gz

    # less $read2 | head -n 400000 | pigz > $outdir/stat_abortive/$sampleid.100K.R2.fastq.gz
    echo "Downsampling to 100K reads..."

    # ## OLD VERSION: polyA
    # $cutadapt -j $thread_trim \
    #     -q 20 \
    #     -a "A{11};min_overlap=11" \
    #     -a "G{13};min_overlap=13" \
    #     --trim-n \
    #     --no-indels \
    #     --json $outdir/stat_abortive/$sampleid.trimming_report.txt \
    #     -e 2 \
    #     -o $outdir/stat_abortive/${sampleid}_polyA_trimmed.R2.fastq.gz \
    #     $outdir/stat_abortive/$sampleid.100K.R2.fastq.gz

    ## NEW VERSION: polyN
    $cutadapt -j $thread_trim \
        -q 20 \
        -a "TCTGGCCTTGCACCTCAAGCA" \
        -a "G{13};min_overlap=13" \
        --trim-n \
        --no-indels \
        --json $outdir/stat_abortive/$sampleid.trimming_report.txt \
        -e 2 \
        -o $outdir/stat_abortive/${sampleid}_polyA_trimmed.R2.fastq.gz \
        $outdir/stat_abortive/$sampleid.100K.R2.fastq.gz


    $seqkit fx2tab $outdir/stat_abortive/${sampleid}_polyA_trimmed.R2.fastq.gz \
        -l -i -Q -n > $outdir/stat_abortive/$sampleid.len.stat.txt
    awk '{print $2}' $outdir/stat_abortive/$sampleid.len.stat.txt > $outdir/stat_abortive/$sampleid.len.stat.tmp
    mv $outdir/stat_abortive/$sampleid.len.stat.tmp $outdir/stat_abortive/$sampleid.len.stat.txt

    $Rscript $src/plot_abortive_distribution.R $outdir/stat_abortive/$sampleid.len.stat.txt $outdir/stat_abortive/$sampleid

}

function barcode_calling(){
    if [[ ! -d $outdir/barcode ]];then 
        mkdir -p $outdir/barcode
    fi 
    # export PERL5LIB="/usr/lib64/perl5/vendor_perl"
    read1=$outdir/trim/${sampleid}_IVT_R1.fastq.gz
    read2=$outdir/trim/${sampleid}_IVT_R2.fastq.gz
      
    if [[ ! -s $outdir/barcode/$sampleid.umi_cor.info ]];then
        $BST_src/fastq2BcUmi -i1 $read1 \
            -i2 $read2 \
            -d $outdir/barcode \
            -p $sampleid \
            -n $SLURM_CPUS_PER_TASK
    else
        echo "fastq2BCUmi is finished!"
    fi 

    if [[ $n_line -eq "-1" ]];then 
        n_line=$(head -n 1 $outdir/barcode/$sampleid.stat | awk '{print $2 * 4}' | xargs)
    fi
    echo "$n_line is processing..."

    $spatial_IVT tag2fq \
        --fastq $read2 \
        --bc_read_map $outdir/barcode/$sampleid.umi \
        -o $outdir/barcode \
        --n_lines $n_line \
        --sampleName $sampleid \
        --threads $SLURM_CPUS_PER_TASK \
        --out_unmapped \
        --umi_cor $outdir/barcode/$sampleid.umi_cor.info \
        --verbose
}


function trim_fq(){
    if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
        thread_trim=12
    else
        thread_trim=$SLURM_CPUS_PER_TASK
    fi 

    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    # -g "^AAGCAGTGGTATCAACGCAGAGTACATAGATGTGTATAAGAGACAG" \
    if [[ ! -s $outdir/trim/${sampleid}_clean.R2.fastq.gz ]];then 
        # $cutadapt -j $thread_trim \
        #     -a "A{11};min_overlap=11" \
        #     -a "G{13};min_overlap=13" \
        #     --trim-n \
        #     --no-indels \
        #     --minimum-length $read_len \
        #     --json $outdir/trim/$sampleid.trimming_report.txt \
        #     -e 2 \
        #     -o $outdir/trim/${sampleid}_clean.R2.fastq.gz \
        #     $outdir/barcode/${sampleid}.barcoded.fastq.gz
        ## NEW VERSION: polyN
        $cutadapt -j $thread_trim \
            -a "TCTGGCCTTGCACCTCAAGCA" \
            -a "G{13};min_overlap=13" \
            --trim-n \
            --no-indels \
            --minimum-length $read_len \
            --json $outdir/trim/$sampleid.trimming_report.txt \
            -e 2 \
            -o $outdir/trim/${sampleid}_clean.R2.fastq.gz \
            $outdir/barcode/${sampleid}.barcoded.fastq.gz

    else
        echo "sequence is trimmed already."
    fi 
}


function align(){

    if [[ ! -d $outdir/align ]];then 
        mkdir -p $outdir/align
    fi 

    if [[ ! -s $outdir/trim/${sampleid}_ME_R1.fastq.gz ]];then 
        $bowtie2 -x $bowti2_idx \
            -U $outdir/trim/${sampleid}_clean.R2.fastq.gz \
            --no-unal \
            -p $SLURM_CPUS_PER_TASK \
            | awk -v OFS='\t' '$0~/^@/ { print; next } { split($1,bc,":"); total=length(bc); print $0 "\tCB:Z:" bc[total-1] "\tUB:Z:" bc[total]}' \
            | $samtools sort -@ $thread_sort -m "12G" \
            > $outdir/align/${sampleid}.tagged.bam
    else
        echo "Align is finished."
    fi 

    $samtools index $outdir/align/${sampleid}.tagged.bam
    $samtools stats $outdir/align/${sampleid}.tagged.bam > $outdir/align/${sampleid}.bam.stat

    ## No need anymore
    # $spatial_IVT tag2bam \
    #     --input_bam $outdir/align/${sampleid}.sorted.bam \
    #     --output_bam $outdir/align/${sampleid}.tagged.bam \
    #     --threads $SLURM_CPUS_PER_TASK 

    # $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/align/${sampleid}.tagged.bam
    # rm $outdir/align/${sampleid}.sorted.bam
    # rm $outdir/align/${sampleid}.sorted.bam.bai

}



function decode_chip(){
    if [[ ! -d $outdir/LinkBcChip ]];then 
        mkdir -p $outdir/LinkBcChip
    fi 

    if [[ $method == "S1000" ]] ; then
        if [[ -n $decode_file ]] ; then
            $BST_src/LinkBcChip \
                -f $decode_file \
                -s $outdir/barcode/$sampleid.umi \
                -u $outdir/barcode/$sampleid.bc_umi_read.tsv \
                -d $outdir/LinkBcChip \
                -p $sampleid
        else
            echo "Skip decoding chip barcode linking..."
        fi
    else
        $BST_src/LinkBcChip \
            -f $decode_file \
            -s $outdir/barcode/$sampleid.umi \
            -u $outdir/barcode/$sampleid.bc_umi_read.tsv \
            -d $outdir/LinkBcChip \
            -p $sampleid \
            -l $outdir/barcode/$sampleid.full_stat \
            -g "NULL"
    fi

}


function call_super_spot(){
    if [[ ! -d $outdir/super_spot ]];then 
        mkdir -p $outdir/super_spot
    fi 

    # generate super-spot map $outdir/super_spot/level_3 etc...
    $python_cv2 $merge_super_spot \
        -i $outdir/${sampleid} \
        -o $outdir/super_spot \
        -L "13,7,6,5,4,3,2,1"
    
    ## add level_barcode tag to bam
    $spatial_IVT levelTag \
        --indir $outdir/super_spot \
        --input_bam $outdir/align/${sampleid}.tagged.bam \
        --output_bam $outdir/align/${sampleid}.super_spot.bam \
        --threads $SLURM_CPUS_PER_TASK \
        --barcode_file $outdir/${sampleid}/barcode.tsv

    if [[ ! -s $outdir/align/${sampleid}.super_spot.bam.bai ]];then 
        $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/align/${sampleid}.super_spot.bam
    fi 
}


function cell_split(){
    if [[ ! -d $outdir/cell_split ]];then 
        mkdir -p $outdir/cell_split
    fi 

    if [[ ! -d $outdir/fragments ]];then 
        mkdir -p $outdir/fragments
    fi 

    ## ------ S1000 ###
    # $segCell \
    ##     -f $img \
    ##     -d $outdir/cell_split
            
    #   ## detect in tissue barcodes
    ##     $python_cv2 $he_detect \
    ##         -e $img \
    ##         -o $outdir/super_spot/ \
    ##         -m $outdir/super_spot/ \
    ##         -r $outdir/cell_split/roi_heAuto.json
    ## ------------------

    if [[ -n $img ]];then
        # $segCell \
        #     -f $img \
        #     -d $outdir/cell_split \
        #     -t "S3000" \
        #     -fs $chanel
        $segCell \
            -f $img \
            -d $outdir/cell_split \
            -t $method 
    else
        echo "Fluorescence image file is not provided!"
        exit 
    fi 
    
    $python_cv2 $search \
        -i $img \
        -o $outdir/cell_split \
        -f -1 \
        --chip_type $method
    
    if [[ $method == "S3000" ]];then 
        $python_cv2 $he_detect \
            -e $img \
            -o $outdir/super_spot/ \
            -m $outdir/super_spot/ \
            -r $outdir/cell_split/roi_heAuto.json \
            -W 42 -H 43 -C 45 -R 51  
    else
        $python_cv2 $he_detect \
            -e $img \
            -o $outdir/super_spot/ \
            -m $outdir/super_spot/ \
            -r $outdir/cell_split/roi_heAuto.json \
            -W 46 -H 46 -C 30 -R 35
    fi 

    $spatial_IVT levelTag \
        --indir $outdir/super_spot \
        --input_bam $outdir/align/${sampleid}.super_spot.bam \
        --output_bam $outdir/align/${sampleid}.cell_split.bam \
        --threads $SLURM_CPUS_PER_TASK \
        --barcode_file $outdir/${sampleid}/barcode.tsv \
        --sc_dict_file $outdir/cell_split/cell_split_result/all_barcode_num.txt

    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/align/${sampleid}.cell_split.bam

    # single cell result 
    $python $src/snapatac2_preprocess.py \
        --input_bam $outdir/align/${sampleid}.cell_split.bam \
        --output_dir $outdir/fragments \
        --sampleid $sampleid \
        --species $species \
        --barcode_tag "SC" \
        --min_fragments_n 10

    ls $outdir/fragments/*SC*metadata.txt | while read meta_file;do 
        prefix_sample=$(basename -s ".metadata.txt" $meta_file)
        $Rscript $src/atac_QC.R 1 $meta_file $outdir/fragments/$prefix_sample.qc.pdf
    done 


}


function snapATAC2(){
    if [[ ! -d $outdir/fragments ]];then 
        mkdir -p $outdir/fragments
    fi 

    $python $src/snapatac2_preprocess.py \
        --input_bam $outdir/align/${sampleid}.super_spot.bam \
        --output_dir $outdir/fragments \
        --sampleid $sampleid \
        --species $species \
        --level_indir $outdir/super_spot \
        --in_tissue \
        --min_fragments_n 10

    # this is for all barcodes (background + in-tissue)
    ls $outdir/fragments/*metadata.txt | while read meta_file;do 
        prefix_sample=$(basename -s ".metadata.txt" $meta_file)
        $Rscript $src/atac_QC.R 1 $meta_file $outdir/fragments/$prefix_sample.qc.pdf
    done 

    $Rscript $src/drawQC.R \
        $outdir/fragments \
        $sampleid \
        $outdir/fragments/$sampleid.n_frag.svg

}


function spatial_position(){
    if [[ ! -d $outdir/spatial ]];then 
        mkdir -p $outdir/spatial
    fi 

    # # in tissue metadat
    # ls $outdir/fragments/*metadata.txt |grep -v SC | while read meta_file;do 
    #     prefix_sample=$(basename -s ".metadata.txt" $meta_file)
    #     level_num=$(echo $prefix_sample | awk '{split($1, a, "L");print a[2]}')
    #     if [[ $level_num == "B" ]] ; then level_num=13; fi
    #     $Rscript $src/atac_QC.R \
    #         $meta_file \
    #         $outdir/fragments/$prefix_sample.in_tissue.qc.pdf \
    #         "TRUE" \
    #         $outdir/super_spot/level_${level_num}/barcodes_in_tissue.tsv.gz
    # done 

    # ## summary for in tissue barcode
    # $Rscript $src/drawQC.R \
    #     $outdir/fragments \
    #     $sampleid \
    #     $outdir/fragments/$sampleid.in_tissue.n_frag.png \
    #     "TRUE" \
    #     $outdir/super_spot

    for level_num in '3' '5' '6' '7' 'B';do
        prefix_sample=${sampleid}_L${level_num}
        input_h5ad=$(ls $outdir/fragments/${sampleid}*L${level_num}*.h5ad | head -n 1 | xargs) 
        
        $python $src/create_gene_activity.py --input_h5ad $input_h5ad

        gene_activity_h5ad=$(ls $outdir/fragments/${sampleid}*L${level_num}*.gene_activity.h5ad | head -n 1| xargs) 
        level_number=$level_num
        if [[ $level_num == "B" ]] ; then level_number=13; fi
        $Rscript $makeSpatialObj \
            $gene_activity_h5ad \
            $outdir/fragments/${prefix_sample}.metadata.txt \
            $outdir/cell_split/he_roi_small.png \
            $outdir/super_spot/level_${level_number}/barcodes_pos.tsv.gz \
            $outdir/spatial \
            $level_number \
            "TRUE"
    done 
}



function bulk(){
    ### calculate as bulk samples
    if [[ ! -d $outdir/bulk ]];then 
        mkdir -p $outdir/bulk
    fi 
    
    ## step 1. dedup by UMI_tools
    $umi_tools dedup \
        --umi-tag="CB" \
        --cell-tag="CB" \
        --extract-umi-method="tag" \
        -I $outdir/align/${sampleid}.super_spot.bam \
        --output-stats=$outdir/bulk/${sampleid}.deduplicated \
        -S $outdir/bulk/${sampleid}.rmdup.bam \
        --method unique 


    ## step 2 shift alignments
    $samtools view -bh -q 30 \
        $outdir/bulk/${sampleid}.rmdup.bam \
    | $samtools sort -@ $thread_sort -m "12G" \
    > $outdir/bulk/${sampleid}.dedup.bam

    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.dedup.bam
    rm $outdir/bulk/${sampleid}.rmdup.bam

    ## filter the chrM reads
    $samtools idxstats -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.dedup.bam \
        | cut -f 1 | grep -v MT \
        | xargs $samtools view -b $outdir/bulk/${sampleid}.dedup.bam > $outdir/bulk/${sampleid}.clean.bam
    
    # $Rscript $src/shiftAlignment.R \
    #     $outdir/bulk/${sampleid}.clean.bam \
    #     $outdir/bulk/${sampleid}.shifted.bam
    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.clean.bam

    effect_genome_size=2652783500
    
    $bamCoverage --numberOfProcessors $SLURM_CPUS_PER_TASK \
        --binSize 10 \
        --normalizeUsing RPGC \
        --effectiveGenomeSize $effective_genome_size \
        --bam $outdir/bulk/${sampleid}.clean.bam \
        -o $outdir/bulk/${sampleid}.clean.bw



    # ## call peak
    # $macs2 callpeak \
    #     -t $outdir/bulk/${sampleid}.shifted.bam \
    #     --keep-dup all \
    #     -f BAM \
    #     -B -g hs \
    #     -n $sampleid \
    #     --nomodel \
    #     --shift -75 \
    #     --extsize 150 \
    #     --outdir $outdir/bulk

}


function stat(){

    if [[ ! -d $outdir/stat ]];then 
        mkdir -p $outdir/stat 
    fi 
    
    total_reads=$($samtools view -@ $SLURM_CPUS_PER_TASK -c results/${sampleid}/${sampleid}.shifted.bam )

    # reads in peaks
    reads_in_peaks=$($bedtools sort -i results/bulk/${sampleid}_peaks.narrowPeak | $bedtools merge -i stdin | $bedtools intersect -u -nonamecheck \
        -a results/${sampleid}/${sampleid}.shifted.bam -b stdin -ubam | $samtools view -@ $SLURM_CPUS_PER_TASK -c)
    # FRiP score
    FRiP=$(awk "BEGIN {print "${reads_in_peaks}"/"${total_reads}"}")

    echo $sampleid $FRiP | tr ' ' '\t' > $outdir/stat/${sampleid}_FRiP.txt

}


## --- this is for test ---
function dedup(){
    ## --- not working ---
    # $picard MarkDuplicates \
    #     -I $outdir/align/${sampleid}.tagged.bam \
    #     -O $outdir/align/${sampleid}.rmdup.bam \
    #     -M $outdir/align/${sampleid}.rmdup.txt \
    #     -REMOVE_DUPLICATES true \
    #     -READ_NAME_REGEX null \
    #     --BARCODE_TAG CB
    ## -------------

    if [[ ! -d $outdir/fragments ]];then 
        mkdir -p $outdir/fragments
    fi 
    $umi_tools dedup \
        --umi-tag="CB" \
        --cell-tag="CB" \
        --extract-umi-method="tag" \
        -I $outdir/align/${sampleid}.tagged.bam \
        --output-stats=$outdir/align/${sampleid}.deduplicated \
        -S $outdir/align/${sampleid}.rmdup.bam \
        --method unique 

    $python $src/snapatac2_preprocess.py \
        --input_bam $outdir/align/${sampleid}.rmdup.bam \
        --output_dir $outdir/fragments \
        --sampleid ${sampleid}_dedup \
        --species $species

    $Rscript $src/atac_QC.R 1 $outdir/fragments/${sampleid}_dedup.metadata.txt $outdir/fragments/${sampleid}_dedup.qc.pdf
}


function dedup_UMI(){


    if [[ ! -d $outdir/dedup_UMI ]];then 
        mkdir -p $outdir/dedup_UMI
    fi 

    $umi_tools dedup \
        --umi-tag="UB" \
        --cell-tag="CB" \
        --extract-umi-method="tag" \
        -I $outdir/align/${sampleid}.tagged.bam \
        --output-stats=$outdir/dedup_UMI/${sampleid}.deduplicated \
        -S $outdir/dedup_UMI/${sampleid}.rmdup.bam \
        --method unique 

    $python $src/snapatac2_preprocess.py \
        --input_bam $outdir/dedup_UMI/${sampleid}.rmdup.bam \
        --output_dir $outdir/dedup_UMI \
        --sampleid $sampleid \
        --species $species

    $Rscript $src/atac_QC.R 1 $outdir/dedup_UMI/${sampleid}.metadata.txt $outdir/dedup_UMI/${sampleid}.qc.pdf
}

## ------- ###


set -x 


case "$option" in
pipe)
    # stat_abortive
    # select_Tn5_reads
    # barcode_calling
    trim_fq
    align
    decode_chip
    call_super_spot
    cell_split
    snapATAC2
    spatial_position
    bulk
    ;;
align)
    align
    ;;
QC)
    stat_abortive
    ;;
atac)
    snapATAC2
    ;;
dedup)
    dedup
    ;;
bulk)
    ## barcode_calling
    ## trim_fq
    ## align
    bulk
    ;;
super_spot)
    call_super_spot
    ;;
dedup_UMI)
    dedup_UMI
    ;;
cell_split)
    cell_split
    snapATAC2
    ;;
decode)
    decode_chip
    ;;
spatial)
    spatial_position
    ;;
*)
    echo "unknown parameter:" $1
    helpdoc
    exit 1
    ;;
esac