#!/usr/bin/env bash

# GitHub-ready entrypoint copied from the development workspace.
# Machine-specific tools and references are resolved from config/pipeline.env.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
export SPATIAL_EPIGENOME_REPO_ROOT="${repo_root}"
# shellcheck source=../lib/common.sh
source "${repo_root}/lib/common.sh"
load_pipeline_config "${repo_root}"
SLURM_CPUS_PER_TASK="${SLURM_CPUS_PER_TASK:-$(threads_or_default 4)}"



set -e
set -o pipefail

helpdoc() {
    cat <<EOF
Description:
    [main::] Spatial ATAC-seq based on IVT data of slide-tags processing pipeline created by Maoxu Wang, Xie Lab, Peking University.
    Last update: 2025.01.12
Usage:
    $run [options]
        -h print user manual information
Options:
    --atac_read1        -- Read1 (.fastq.gz)
    --atac_read2        -- Read2 (.fastq.gz)
    --spatial_read1     -- Read1 (.fastq.gz)
    --spatial_read2     -- Read2 (.fastq.gz)
    --HDMI_read         -- Read (.fastq.gz)
    --sampleid          -- sampleid name specified 
    --species           -- e.g. hg38 or mm10
    --chip_id           -- generated by DBiT chip
    --n_line            -- number of lines to process (default: all lines)
    --outdir            -- output directory
    --DAPI              -- DAPI image (.tif) 
    --HE                -- HE image (.tif) 
    --option            -- steps to run
    --debug             -- debug mode
    --help              -- print manual
EOF
}
ARGS=$(getopt -o o:i:h -l atac_read1:,atac_read2:,spatial_read1:,spatial_read2:,HDMI_read:,sampleid:,species:,chip_id:,n_line:,outdir:,DAPI:,HE:,option:,debug:,help -- "$@")



if [ $? != 0 ]; then
    echo "terminating..." >&2
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
    --atac_read1)
        atac_read1=$2
        shift 2
        ;;
    --atac_read2)
        atac_read2=$2
        shift 2
        ;; 
    --spatial_read1)
        spatial_read1=$2
        shift 2
        ;;
    --spatial_read2)
        spatial_read2=$2
        shift 2
        ;; 
    --HDMI_read)
        HDMI_read=$2
        shift 2
        ;;
    --sampleid)
        sampleid=$2
        shift 2
        ;; 
    --species)
        species=$2
        shift 2
        ;; 
    --chip_id)
        chip_id=$2
        shift 2
        ;;  
    --n_line)
        n_line=$2
        shift 2
        ;;
    -o | --outdir)
        outdir=$2
        shift 2
        ;;
    --DAPI)
        DAPI=$2
        shift 2
        ;;
    --HE)
        HE=$2
        shift 2
        ;;
    --option)
        option=$2
        shift 2
        ;;
    --debug)
        debug=$2
        shift 2
        ;;
    -h | --help)
        helpdoc
        exit 1
        ;;
    --)
        shift
        echo "Parameters recevied."
        break
        ;;
    *)
        echo "unknown parameter:" $1
        helpdoc
        exit 1
        ;;
    esac
done

## ---- inspect arguments ---
### cell barcode on atac read1
if [[ ! $atac_read1 =~ "R1" ]]; then
    echo $atac_read1 "wrong Read1 specified"
    exit
fi
### insert barcode on atac read2
if [[ ! $atac_read2 =~ "R2" ]]; then
    echo $atac_read2 "wrong Read2 specified"
    exit
fi

### cell barcode on atac read1
if [[ ! $spatial_read1 =~ "R1" ]]; then
    echo $spatial_read1 "wrong Read1 specified"
    exit
fi
### spatial barcode on atac read2
if [[ ! $spatial_read2 =~ "R2" ]]; then
    echo $spatial_read2 "wrong Read2 specified"
    exit
fi

if [[ ! -n $outdir ]]; then outdir="./result"; fi
if [[ ! -n $n_line ]]; then n_line="-1"; fi
if [[ ! -n $option ]]; then option="pipe"; fi

if [[ ! -n $debug ]]; then debug=False; fi

if [[ ! -n $sampleid ]]; then
    echo "Please specify sampleid name"
    exit
fi

if [[ ! -n $species ]]; then
    echo "Please specify species"
    exit
fi

if [[ $SLURM_CPUS_PER_TASK > 12 ]];then 
    sort_thread=12
else
    sort_thread=$SLURM_CPUS_PER_TASK
fi 


## ---- SOFTWARE --- 
trim_galore="${TRIM_GALORE:-trim_galore}"
cutadapt="${CUTADAPT:-cutadapt}"
bedtools="${BEDTOOLS:-bedtools}"
bowtie2="${BOWTIE2:-bowtie2}"
samtools="${SAMTOOLS:-samtools}"
picard="${PICARD:-picard}"
Rscript="${RSCRIPT:-Rscript}"
macs2="${MACS2:-macs2}"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
umi_tools="${UMI_TOOLS:-umi_tools}"
spatial_IVT="${SPATIAL_IVT:-spatial_IVT}"
seqkit="${SEQKIT:-seqkit}"
python="${PYTHON:-python}"
python_cv2="${PYTHON_CV2:-python}"
bigWigToBedGraph="${BIGWIG_TO_BEDGRAPH:-bigWigToBedGraph}"
bedGraphToBigWig="${BEDGRAPH_TO_BIGWIG:-bedGraphToBigWig}"

## --- custom scripts
src="${SPATIAL_EPIGENOME_SCRIPT_DIR:-${repo_root}/scripts}"
extract_barcodes="$src/DBiT/extract_barcodes.py"
mtx2svg="$src/DBiT/position_matrix.pl"
createSeuratObj="$src/DBiT/createSeuratObj.R"
spatial_metadata="$src/DBiT/metadata_seurat_spatial.py"

## ---- FILES ---
hg38_idx="${HG38_BOWTIE2_INDEX:-/path/to/bowtie2/hg38}"
mm10_idx="${MM10_BOWTIE2_INDEX:-/path/to/bowtie2/mm10}"
chrom_size_var="${species^^}_CHROM_SIZES"
chromSize="${!chrom_size_var}"
hg38_autosome="${HG38_AUTOSOME_BED:-/path/to/hg38.autosome.txt}"
mm10_autosome="${MM10_AUTOSOME_BED:-/path/to/mm10.autosome.txt}"
rmsk_hg38="${HG38_RMSK_BED:-/path/to/hg38.rmsk.bed}"
rmsk_mm10="${MM10_RMSK_BED:-/path/to/mm10.rmsk.bed}"

read_len=20

declare -A Ref_fa
Ref_fa["hg38"]=$hg38_idx
Ref_fa["mm10"]=$mm10_idx
bowti2_idx=${Ref_fa[$species]}

declare -A effective_size
effective_size["hg38"]=2913022398
effective_size["mm10"]=2652783500
effective_genome_size=${effective_size[$species]}


if [[ $SLURM_CPUS_PER_TASK -ge 8 ]]; then
    thread_trim=8
else
    thread_trim=$SLURM_CPUS_PER_TASK
fi 

if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
    thread_sort=12
else
    thread_sort=$SLURM_CPUS_PER_TASK
fi 


function stat_abortive(){
    
    if [[ ! -d $outdir/stat_abortive ]];then 
        mkdir -p $outdir/stat_abortive
    fi 
    thread_trim=8

    less $atac_read2 | head -n 400000 | pigz > $outdir/stat_abortive/$sampleid.100K.R1.fastq.gz

    echo "Downsampling to 100K reads..."

    $cutadapt -j $thread_trim \
        -a "A{9};max_error_rate=0.2;min_overlap=3" \
        --trim-n \
        --no-indels \
        --json $outdir/stat_abortive/$sampleid.trimming_report.txt \
        -e 2 \
        -o $outdir/stat_abortive/${sampleid}_polyA_trimmed.R1.fastq.gz \
        $outdir/stat_abortive/$sampleid.100K.R1.fastq.gz

    $seqkit fx2tab $outdir/stat_abortive/${sampleid}_polyA_trimmed.R1.fastq.gz \
        -l -i -Q -n > $outdir/stat_abortive/$sampleid.len.stat.txt
    awk '{print $2}' $outdir/stat_abortive/$sampleid.len.stat.txt > $outdir/stat_abortive/$sampleid.len.stat.tmp
    mv $outdir/stat_abortive/$sampleid.len.stat.tmp $outdir/stat_abortive/$sampleid.len.stat.txt

    $Rscript $src/plot_abortive_distribution.R $outdir/stat_abortive/$sampleid.len.stat.txt $outdir/stat_abortive/$sampleid

}


function barcode_calling(){
    if [[ ! -d $outdir/barcode ]];then 
        mkdir -p $outdir/barcode
    fi 
    # export PERL5LIB="/usr/lib64/perl5/vendor_perl"

    if [ ! -s $atac_read1 ]; then
        echo $atac_read1 "Read1 not exist"
        exit
    fi

    if [ ! -s $atac_read2 ]; then
        echo $atac_read2 "Read2 not exist"
        exit
    fi


    if [[ $n_line -eq "-1" ]];then 
        if [[ -s $outdir/${sampleid}.total_readsN.txt ]];then
            n_line=$(head -n 1 $outdir/${sampleid}.total_readsN.txt | awk '{print $1 * 4}' | xargs) 
            echo "$n_line is processing..."
        else
            echo "All lines is processing..."
        fi
    fi
 
    $python_cv2 $extract_barcodes \
        --read1 $atac_read1 \
        --read2 $atac_read2 \
        -o $outdir/barcode \
        --n_lines $n_line \

        --sampleName $sampleid \
        --threads $SLURM_CPUS_PER_TASK
}


function trim_fq(){
    if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
        thread_trim=12
    else
        thread_trim=$SLURM_CPUS_PER_TASK
    fi 

    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    if [[ ! -s $outdir/trim/${sampleid}_clean.R2.fastq.gz ]];then 
        $cutadapt -j $thread_trim \
            -a "A{9};max_error_rate=0.2;min_overlap=3" \
            --trim-n \
            --no-indels \
            --minimum-length $read_len \
            --json $outdir/trim/$sampleid.trimming_report.txt \
            -e 2 \
            -o $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
            $outdir/barcode/${sampleid}.R1.barcoded.fastq.gz
    else
        echo "sequence is trimmed already."
    fi 
}


function trim_Nextera(){
    if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
        thread_trim=12
    else
        thread_trim=$SLURM_CPUS_PER_TASK
    fi 

    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    if [[ ! -s $outdir/trim/${sampleid}_clean.R2.fastq.gz ]];then 
        $trim_galore \
            --paired \
            --nextera \
            --stringency 5 \
            --cores $thread_trim \
            -o $outdir/trim \
            $outdir/barcode/${sampleid}.R1.barcoded.fastq.gz \
            $outdir/barcode/${sampleid}.R2.barcoded.fastq.gz
    else
        echo "sequence is trimmed already."
    fi 

    ## CB:UMI:readname
    $bowtie2 -x $bowti2_idx \
        --no-unal \
        -X 2000 \
        -1 $outdir/trim/${sampleid}.R1_val_1.fq.gz \
        -2 $outdir/trim/${sampleid}.R2_val_2.fq.gz \
        -p $SLURM_CPUS_PER_TASK \
        | awk -v OFS='\t' '$0~/^@/ { print; next } { split($1,bc,":"); total=length(bc); print $0 "\tCB:Z:" bc[1] "\tUB:Z:" bc[2]}' \
        | $samtools sort -@ $thread_sort -m "12G" \
        > $outdir/align/${sampleid}.sorted.bam

    $samtools index $outdir/align/${sampleid}.sorted.bam
    $samtools stats $outdir/align/${sampleid}.sorted.bam > $outdir/align/${sampleid}.bam.stat

}


function align(){

    if [[ ! -d $outdir/align ]];then 
        mkdir -p $outdir/align
    fi 

    if [[ ! -s $outdir/align/${sampleid}.sorted.bam ]];then 
        $bowtie2 -x $bowti2_idx \
            -U $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
            --no-unal \
            -p $SLURM_CPUS_PER_TASK \
            | awk -v OFS='\t' '$0~/^@/ { print; next } { split($1,bc,":"); total=length(bc); print $0 "\tCB:Z:" bc[1] "\tUB:Z:" bc[2]}' \
            | $samtools sort -@ $thread_sort -m "12G" \
            > $outdir/align/${sampleid}.sorted.bam
    else
        echo "Align is finished."
    fi 

    $samtools index $outdir/align/${sampleid}.sorted.bam
    $samtools stats $outdir/align/${sampleid}.sorted.bam > $outdir/align/${sampleid}.bam.stat

}

function snapATAC2(){
    if [[ ! -d $outdir/fragments ]];then 
        mkdir -p $outdir/fragments
    fi 
    
    $python $src/snapatac2_preprocess.py \
        --input_bam $outdir/align/${sampleid}.sorted.bam \
        --output_dir $outdir/fragments \
        --sampleid $sampleid \
        --species $species \
        --max_iter 1 \
        --n_features 50000

    #ls $outdir/fragments/*bw | while read ff;do
    #    sample=$(basename -s ".bw" $ff)
    #    $bigWigToBedGraph $ff $outdir/fragments/${sample}.bg
    #    $bedGraphToBigWig $outdir/fragments/${sample}.bg \
    #        $chromSize \
    #        $outdir/fragments/${sample}.bigWig
    #done 

    ls $outdir/fragments/*metadata.txt | while read meta_file;do 
        prefix_sample=$(basename -s ".metadata.txt" $meta_file)
        $Rscript $src/atac_QC.R 10000 $meta_file $outdir/fragments/$prefix_sample.qc.pdf
    done 

}


function spatial_position(){
    if [[ ! -d $outdir/spatial/${sampleid} ]];then 
        mkdir -p $outdir/spatial/${sampleid}
    fi 
    echo $decode_file

    $python $src/gene_activity.py \
        --input_h5ad $outdir/fragments/${sampleid}_CB.h5ad \
        --species $species \
        --barcode_file $decode_file \
        --outdir $outdir/spatial

    # # detect in tissue barcodes
    perl $mtx2svg $outdir/fragments/${sampleid}_CB.exp.tsv \
        > $outdir/spatial/${sampleid}.raw.svg
    $python $src/svg2png.py \
        -i $outdir/spatial/${sampleid}.raw.svg \
        -o $outdir/spatial/${sampleid}/tissue_lowres_image.png

    $python_cv2 $src/makeMetadata.py \
        --decode_file $decode_file \
        --img_path $outdir/spatial/${sampleid}/tissue_lowres_image.png \
        -o $outdir/spatial/${sampleid}

    # if [[ -s $outdir/fragments/${sampleid}_CB.500.metadata.txt ]];then
    #     mv $outdir/fragments/${sampleid}_CB.500.metadata.txt $outdir/fragments/${sampleid}_CB.metadata.txt
    # fi 
    $Rscript $createSeuratObj \
        $outdir/fragments/${sampleid}_CB.exp.tsv \
        $outdir/fragments/${sampleid}_CB.metadata.txt \
        $outdir/spatial/spatial_barcodes.txt \
        $outdir/spatial/${sampleid}.spatial.rds \
        $outdir/spatial/${sampleid}

}


function bulk(){
    ### calculate as bulk samples
    if [[ ! -d $outdir/bulk ]];then 
        mkdir -p $outdir/bulk
    fi 

    ## filter the chrM reads
    $samtools idxstats -@ $SLURM_CPUS_PER_TASK $outdir/align/${sampleid}.sorted.bam \
        | cut -f 1 | grep -v MT \
        | xargs $samtools view -b $outdir/align/${sampleid}.sorted.bam > $outdir/bulk/${sampleid}.clean.bam
    
    # $Rscript $src/shiftAlignment.R \
    #     $outdir/bulk/${sampleid}.clean.bam \
    #     $outdir/bulk/${sampleid}.shifted.bam
    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.clean.bam

    effect_genome_size=2652783500
    
    $bamCoverage --numberOfProcessors $SLURM_CPUS_PER_TASK \
        --binSize 10 \
        --normalizeUsing RPGC \
        --effectiveGenomeSize $effective_genome_size \
        --bam $outdir/bulk/${sampleid}.clean.bam \
        -o $outdir/bulk/${sampleid}.clean.bw

}

function stat(){

    if [[ ! -d $outdir/stat ]];then 
        mkdir -p $outdir/stat 
    fi 
    
    invalid_barcode_reads=$(less $outdir/barcode/${sampleid}.unmapped.tsv.gz | awk '{sum+=$2}END{print sum}')
    valid_barcode_reads=$(less $outdir/barcode/${sampleid}.mapped.tsv.gz | awk '{sum+=$2}END{print sum}')
    total_raw_reads=$(echo "scale=2; $invalid_barcode_reads + $valid_barcode_reads" | bc | xargs)
    valid_barcode_percent=$(echo "scale=2; $valid_barcode_reads / $total_raw_reads * 100" | bc | xargs)
    reads_passing_filter=$(grep 'output":' $outdir/trim/${sampleid}.trimming_report.txt | awk '{print $2}' | head -n 1 | sed 's/,//g')
    reads_passing_filter_rate=$(echo "scale=2; $reads_passing_filter / $valid_barcode_reads * 100" | bc | xargs)
    
    unique_align_reads=$($samtools view -q 20 -c -@ 12 $outdir/align/${sampleid}.sorted.bam | xargs)

    align_rate=$(echo "scale=2; $unique_align_reads / $reads_passing_filter * 100" | bc | xargs)

    if [[ ! -s ${outdir}/stat/stat.txt ]]; then
        echo -e "SampleID\tSpecies\tTotal_reads\tBarcode_valid_percent\tReads_high_qualtity_percent\tUnique_aligned_reads\tUnique_align_rate" > ${outdir}/stat/stat.txt
    fi

    echo -e "$sampleid\t${species}\t" \
        "${total_raw_reads}\t" \
        "${valid_barcode_percent}%\t" \
        "${reads_passing_filter_rate}%\t" \
        "${unique_align_reads}%\t" \
        "${align_rate}\t" \
        >>${outdir}/stat/stat.txt

}


## ------- ###


set -x 


case "$option" in
pipe)
    #stat_abortive
    barcode_calling
    trim_fq
    align 
    snapATAC2
    spatial_position
    stat
    bulk
    ;;
align)
    align
    ;;
QC)
    stat_abortive
    ;;
atac)
    snapATAC2
    ;;
dedup)
    dedup
    ;;
bulk)
    bulk
    # trim_Nextera
    ;;
dedup_UMI)
    dedup_UMI
    ;;
spatial)
    spatial_position
    ;;
no_IVT)
    paired=FALSE
    barcode_calling
    trim_Nextera
    paired=TRUE
    snapATAC2
    bulk
    spatial_position
    ;;
*)
    echo "unknown parameter:" $1
    helpdoc
    exit 1
    ;;
esac