#!/usr/bin/env bash

# GitHub-ready entrypoint copied from the development workspace.
# Machine-specific tools and references are resolved from config/pipeline.env.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
export SPATIAL_EPIGENOME_REPO_ROOT="${repo_root}"
# shellcheck source=../lib/common.sh
source "${repo_root}/lib/common.sh"
load_pipeline_config "${repo_root}"
SLURM_CPUS_PER_TASK="${SLURM_CPUS_PER_TASK:-$(threads_or_default 4)}"


set -e
set -o pipefail

helpdoc() {
    cat <<EOF
Description:
    [main::] Spatial ATAC-seq based on IVT data of 10X visium HD processing pipeline created by Maoxu Wang, Xie Lab, Peking University.
    Last update: 2025.02.07
Usage:
    $run [options]
        -h print user manual information
Options:
    --read1             -- Read1 (.fastq.gz)
    --read2             -- Read2 (.fastq.gz)
    --tif               -- tif
    --area              -- e.g. A1,D1
    --sampleid          -- sampleid name specified 
    --species           -- e.g. hg38 or mm10
    --spaceranger_bam   -- generated by spaceranger 10X
    --n_line            -- number of lines to process (default: all lines)
    --outdir            -- output directory
    --img               -- fluorescence or HE image
    --option            -- steps to run
    --debug             -- debug mode
    --help              -- print manual
EOF
}
ARGS=$(getopt -o o:i:h -l read1:,read2:,tif:,slide:,area:,sampleid:,species:,spaceranger_bam:,n_line:,outdir:,img:,paired:,option:,debug:,mode:,help -- "$@")


if [ $? != 0 ]; then
    echo "terminating..." >&2
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
    --read1)
        read1=$2
        shift 2
        ;;
    --read2)
        read2=$2
        shift 2
        ;; 
    --tif)
        tif=$2
        shift 2
        ;; 
    --area)
        area=$2
        shift 2
        ;; 
    --slide)
        slide=$2
        shift 2
        ;; 
    --sampleid)
        sampleid=$2
        shift 2
        ;; 
    --species)
        species=$2
        shift 2
        ;; 
    --spaceranger_bam)
        spaceranger_bam=$2
        shift 2
        ;;  
    --n_line)
        n_line=$2
        shift 2
        ;;
    --paired)
        paired=$2
        shift 2
        ;;
    -o | --outdir)
        outdir=$2
        shift 2
        ;;
    --img)
        img=$2
        shift 2
        ;;
    --option)
        option=$2
        shift 2
        ;;
    --debug)
        debug=$2
        shift 2
        ;;
    --mode)
        mode=$2
        shift 2
        ;;
    -h | --help)
        helpdoc
        exit 1
        ;;
    --)
        shift
        echo "Parameters recevied."
        break
        ;;
    *)
        echo "unknown parameter:" $1
        helpdoc
        exit 1
        ;;
    esac
done

if [[ ! $read1 =~ "R1" ]]; then
    echo $read1 "wrong Read1 specified"
    exit
fi

if [[ ! $read2 =~ "R2" ]]; then
    echo $read2 "wrong Read2 specified"
    exit
fi

if [[ ! -n $outdir ]]; then outdir="./result"; fi
if [[ ! -n $n_line ]]; then n_line="-1"; fi
if [[ ! -n $option ]]; then option="pipe"; fi
if [[ ! -n $mode ]]; then mode="atac"; fi
if [[ ! -n $paired ]]; then 
    paired="FALSE"
    echo "Using Single-end mode"
else
    echo "Using PE: $paired"
fi

echo "Option: $option"
if [[ ! -n $debug ]]; then debug=False; fi

if [[ ! -n $sampleid ]]; then
    echo "Please specify sampleid name"
    exit
fi

if [[ ! -n $species ]]; then
    echo "Please specify species"
    exit
fi

if [[ $SLURM_CPUS_PER_TASK > 12 ]];then 
    sort_thread=12
else
    sort_thread=$SLURM_CPUS_PER_TASK
fi 

trim_galore="${TRIM_GALORE:-trim_galore}"
cutadapt="${CUTADAPT:-cutadapt}"
bedtools="${BEDTOOLS:-bedtools}"
bowtie2="${BOWTIE2:-bowtie2}"
samtools="${SAMTOOLS:-samtools}"
src="${SPATIAL_EPIGENOME_SCRIPT_DIR:-${repo_root}/scripts}"
visium_src="${src}/visium_hd_atac"
umi_tools="${UMI_TOOLS:-umi_tools}"
spatial_IVT="${SPATIAL_IVT:-spatial_IVT}"
seqkit="${SEQKIT:-seqkit}"
python="${PYTHON:-python}"
python_cv2="${PYTHON_CV2:-python}"
merge_super_spot="${MERGE_SUPER_SPOT:-levelMatrix.py}"
picard="${PICARD:-picard}"
Rscript="${RSCRIPT:-Rscript}"
macs2="${MACS2:-macs2}"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
extract_barcodes="$src/visium_hd_atac/extract_barcodes.py"
bamCoverage="${BAMCOVERAGE:-bamCoverage}"
createSeuratObj="$src/visium_hd_atac/createSeuratObj.R"
bigWigToBedGraph="${BIGWIG_TO_BEDGRAPH:-bigWigToBedGraph}"
bedGraphToBigWig="${BEDGRAPH_TO_BIGWIG:-bedGraphToBigWig}"
picard="${PICARD:-picard}"
create_gene_activity="${src}/create_gene_activity.py"
signac_chromVar="$src/DBiT//signac_chromVar.R"
spaceranger="${SPACERANGER:-spaceranger}"
fastqc="${FASTQC:-fastqc}"
macs2="${MACS2:-macs2}"
run_signac="${src}/visium_hd_atac/run_signac.R"
diffuse_distance="${src}/visium_hd_atac/analyze_diffusion_distance.R"
swap_count="${repo_root}/tools/cal_swap_score.sh"

hg38_idx="${HG38_BOWTIE2_INDEX:-/path/to/bowtie2/hg38}"
mm10_idx="${MM10_BOWTIE2_INDEX:-/path/to/bowtie2/mm10}"
chrom_size_var="${species^^}_CHROM_SIZES"
chromSize="${!chrom_size_var}"
ref_hg38="${HG38_10X_GEX_REF:-/path/to/refdata-gex-GRCh38}"
ref_mm10="${MM10_10X_GEX_REF:-/path/to/refdata-gex-mm10}"

hg38_autosome="${HG38_AUTOSOME_BED:-/path/to/hg38.autosome.txt}"
mm10_autosome="${MM10_AUTOSOME_BED:-/path/to/mm10.autosome.txt}"
rmsk_hg38="${HG38_RMSK_BED:-/path/to/hg38.rmsk.bed}"
rmsk_mm10="${MM10_RMSK_BED:-/path/to/mm10.rmsk.bed}"
probe="${repo_root}/resources/visium_hd_atac/Visium_Mouse_Transcriptome_Probe_Set_v2.0_mm10-2020-A.csv"

read_len=20

declare -A Ref_fa
Ref_fa["hg38"]=$hg38_idx
Ref_fa["mm10"]=$mm10_idx
bowti2_idx=${Ref_fa[$species]}

declare -A MACS2_GENOME=(
  [hg38]="hs"
  [mm10]="mm"
)

declare -A resolution_list
resolution_list["L2"]="002um"
resolution_list["L8"]="008um"
resolution_list["CB"]="016um"
resolution_list["LS"]="050um"

declare -A effective_size
effective_size["hg38"]=2913022398
effective_size["mm10"]=2652783500
effective_genome_size=${effective_size[$species]}

declare -A visium_refs
visium_refs["hg38"]=$ref_hg38
visium_refs["mm10"]=$ref_mm10
visium_ref=${visium_refs[$species]}

if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
    thread_trim=12
else
    thread_trim=$SLURM_CPUS_PER_TASK
fi 

if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
    thread_sort=12
else
    thread_sort=$SLURM_CPUS_PER_TASK
fi 

if [ ! -s $read1 ]; then
    echo $read1 "Read1 not exist"
    exit
fi

if [ ! -s $read2 ]; then
    echo $read2 "Read2 not exist"
    exit
fi

function run_spaceranger(){

    slide_number=$(basename -s ".vlf" $slide)
    cd $outdir
    if [[ ! -d $outdir/trim/R2/ ]];then
        mkdir -p $outdir/trim/R2/
    fi

    $cutadapt -j $thread_trim \
        -G "^GGAGTGTGAAGACAGAGATGTGTATAAGAGACAG" \
        -e 0.1 \
        -o $outdir/trim/R2/${sampleid}_IVT.R1.fastq.gz \
        -p $outdir/trim/R2/${sampleid}_IVT.R2.fastq.gz \
        $read1 $read2

    mv $outdir/trim/R2/${sampleid}_IVT.R1.fastq.gz $outdir/trim/R2/${sampleid}_S1_L002_R1_001.fastq.gz
    mv $outdir/trim/R2/${sampleid}_IVT.R2.fastq.gz $outdir/trim/R2/${sampleid}_S1_L002_R2_001.fastq.gz
    fastq_dir=$(dirname $outdir/trim/R2/${sampleid}_S1_L002_R2_001.fastq.gz)

    $spaceranger count --id=$sampleid \
        --transcriptome=$visium_ref \
        --create-bam=true \
        --fastqs=$fastq_dir \
        --sample=$sampleid \
        --cytaimage=$tif \
        --slide=$slide_number \
        --slidefile=$slide \
        --area=$area \
        --localcores=$SLURM_CPUS_PER_TASK \
        --project=$sampleid \
        --localmem=150 \
        --custom-bin-size 50 \
        --loupe-alignment ../data/${sampleid}.json
    cd $outdir/..

}

function select_Tn5_reads(){
    if [[ ! -d $outdir/trim/R1 ]];then 
        mkdir -p $outdir/trim/R1
    fi 

    if [[ ! -d $outdir/trim/R2 ]];then 
        mkdir -p $outdir/trim/R2
    fi 
    
    ## Select by R2
    $cutadapt -j $thread_trim \
        -G "^GGAGTGTGAAGACAGAGATGTGTATAAGAGACAG" \
        -e 0.1 \
        -o $outdir/trim/R2/${sampleid}_IVT.R1.fastq.gz \
        -p $outdir/trim/R2/${sampleid}_IVT.R2.fastq.gz \
        --untrimmed-output $outdir/trim/R2/${sampleid}_RNA_R1.fastq.gz \
        --untrimmed-paired-output $outdir/trim/R2/${sampleid}_RNA_R2.fastq.gz \
        $read1 $read2
    
}  

function stat_abortive(){
    
    if [[ ! -d $outdir/stat_abortive ]];then 
        mkdir -p $outdir/stat_abortive
    fi 

    head -n 400000 <(zcat $outdir/trim/R2/${sampleid}*R2*fastq.gz) | pigz > $outdir/stat_abortive/$sampleid.100K.R2.fastq.gz
    
    echo "Downsampling to 100K reads..."

    $cutadapt -j $thread_trim \
        -a "A{13};min_overlap=7" \
        --json $outdir/stat_abortive/$sampleid.trimming_report.txt \
        -e 2 \
        -o $outdir/stat_abortive/${sampleid}_polyA_trimmed.R2.fastq.gz \
        $outdir/stat_abortive/$sampleid.100K.R2.fastq.gz

    $fastqc -t $thread_trim $outdir/stat_abortive/${sampleid}_polyA_trimmed.R2.fastq.gz
    $seqkit fx2tab $outdir/stat_abortive/${sampleid}_polyA_trimmed.R2.fastq.gz \
        -l -i -Q -n > $outdir/stat_abortive/$sampleid.len.stat.txt
    awk '{print $2}' $outdir/stat_abortive/$sampleid.len.stat.txt > $outdir/stat_abortive/$sampleid.len.stat.tmp
    mv $outdir/stat_abortive/$sampleid.len.stat.tmp $outdir/stat_abortive/$sampleid.len.stat.txt

    $Rscript $src/plot_abortive_distribution.R $outdir/stat_abortive/$sampleid.len.stat.txt $outdir/stat_abortive/$sampleid

}


function barcode_calling(){
    if [[ ! -d $outdir/barcode ]];then 
        mkdir -p $outdir/barcode
    fi 

    if [[ $n_line -eq "-1" ]];then 
        n_line=$(tail -n 1  $outdir/${sampleid}/outs/metrics_summary.csv | awk -F, '{print $2 }' | xargs) 
        echo "$n_line is processing..."
    fi
    
    if [[ ! -s $outdir/${sampleid}/outs/possorted_genome_bam.sam.gz ]];then 
        $samtools view \
            -@ $SLURM_CPUS_PER_TASK \
            $outdir/${sampleid}/outs/possorted_genome_bam.bam \
            | pigz -p $thread_sort > $outdir/${sampleid}/outs/possorted_genome_bam.sam.gz
    fi 
    if [[ $paired == "TRUE" ]];then
        $python_cv2 $extract_barcodes \
            -i $outdir/${sampleid}/outs/possorted_genome_bam.sam.gz \
            -o $outdir/barcode \
            --sample $sampleid \
            --threads $SLURM_CPUS_PER_TASK \
            --n_lines $n_line \
            --paired
    else
        $python_cv2 $extract_barcodes \
            -i $outdir/${sampleid}/outs/possorted_genome_bam.sam.gz \
            -o $outdir/barcode \
            --sample $sampleid \
            --threads $SLURM_CPUS_PER_TASK \
            --n_lines $n_line

    fi
}


function trim_fq(){
    if [[ $SLURM_CPUS_PER_TASK -ge 12 ]]; then
        thread_trim=12
    else
        thread_trim=$SLURM_CPUS_PER_TASK
    fi 

    if [[ ! -d $outdir/trim ]];then 
        mkdir -p $outdir/trim
    fi 

    if [[ $paired == "TRUE" ]];then

        $cutadapt -j $thread_trim \
            -q 20 \
            -A "A{13};min_overlap=7" \
            -g "T{13};min_overlap=5" \
            -a "CTGTCTCTTATACACATCTCTGTCTTCACACTCC" \
            -e 0.2 \
            --trim-n \
            --minimum-length $read_len \
            --json $outdir/trim/$sampleid.trimming_report.txt \
            -o $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
            -p $outdir/trim/${sampleid}_clean_barcoded.R2.fastq.gz \
            $outdir/barcode/${sampleid}.R1.barcoded.fastq.gz \
            $outdir/barcode/${sampleid}.R2.barcoded.fastq.gz

    else
        if [[ ! -s $outdir/trim/${sampleid}_clean_barcoded.R2.fastq.gz ]];then 
            $cutadapt -j $thread_trim \
                -q 20 \
                -a "A{13};min_overlap=7" \
                --trim-n \
                --minimum-length $read_len \
                --json $outdir/trim/$sampleid.trimming_report.txt \
                -e 2 \
                -o $outdir/trim/${sampleid}_clean_barcoded.R2.fastq.gz \
                $outdir/barcode/${sampleid}.R2.barcoded.fastq.gz
        else
            echo "sequence is trimmed already."
        fi 
    fi


}


function align(){

    if [[ ! -d $outdir/align ]];then 
        mkdir -p $outdir/align
    fi 

    if [[ ! -s $outdir/align/${sampleid}.sorted.bam ]];then 

        if [[ $paired == "TRUE" ]];then
            $bowtie2 -x $bowti2_idx \
                -1 $outdir/trim/${sampleid}_clean_barcoded.R1.fastq.gz \
                -2 $outdir/trim/${sampleid}_clean_barcoded.R2.fastq.gz \
                --no-unal \
                -p $SLURM_CPUS_PER_TASK \
                | awk -v OFS='\t' '$0~/^@/ { print; next } { 
                    split($1, bc, ":"); 
                    split(bc[1], cellbarcode, "_");
                    X_8 = sprintf("%05d", cellbarcode[3] / 4);
                    Y_8 = sprintf("%05d", cellbarcode[4] / 4);
                    X_16 = sprintf("%05d", cellbarcode[3] / 8);
                    Y_16 = sprintf("%05d", cellbarcode[4] / 8);
                    X_50 = sprintf("%05d", cellbarcode[3] / 25);
                    Y_50 = sprintf("%05d", cellbarcode[4] / 25);
                    updated_8 = "s_008um_"X_8"_"Y_8;
                    updated_16 = "s_016um_"X_16"_"Y_16;
                    updated_50 = "s_050um_"X_50"_"Y_50;
                    print $0 "\tL2:Z:" bc[1] "\tUB:Z:" bc[2] "\tL8:Z:" updated_8 "\tCB:Z:" updated_16 "\tLS:Z:" updated_50}' \
                | $samtools sort -@ $thread_sort -m "12G" \
                > $outdir/align/${sampleid}.sorted.bam
        else
            $bowtie2 -x $bowti2_idx \
                -U $outdir/trim/${sampleid}_clean_barcoded.R2.fastq.gz \
                --no-unal \
                -p $SLURM_CPUS_PER_TASK \
                | awk -v OFS='\t' '$0~/^@/ { print; next } { 
                    split($1, bc, ":"); 
                    split(bc[1], cellbarcode, "_");
                    X_8 = sprintf("%05d", cellbarcode[3] / 4);
                    Y_8 = sprintf("%05d", cellbarcode[4] / 4);
                    X_16 = sprintf("%05d", cellbarcode[3] / 8);
                    Y_16 = sprintf("%05d", cellbarcode[4] / 8);
                    X_50 = sprintf("%05d", cellbarcode[3] / 25);
                    Y_50 = sprintf("%05d", cellbarcode[4] / 25);
                    updated_8 = "s_008um_"X_8"_"Y_8;
                    updated_16 = "s_016um_"X_16"_"Y_16;
                    updated_50 = "s_050um_"X_50"_"Y_50;
                    print $0 "\tL2:Z:" bc[1] "\tUB:Z:" bc[2] "\tL8:Z:" updated_8 "\tCB:Z:" updated_16 "\tLS:Z:" updated_50}' \
                | $samtools sort -@ $thread_sort -m "12G" \
                > $outdir/align/${sampleid}.sorted.bam 
            
            $samtools index $outdir/align/${sampleid}.sorted.bam
            $samtools stats $outdir/align/${sampleid}.sorted.bam > $outdir/align/${sampleid}.bam.stat
        fi
    else
        echo "Align is finished."
    fi 

}

function snapATAC2(){
    if [[ ! -d $outdir/fragments ]];then 
        mkdir -p $outdir/fragments
    fi 

    for res in "CB" "LS";do
        
        zcat $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/filtered_feature_bc_matrix/barcodes.tsv.gz \
            | sed 's/-1//' | pigz > $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/filtered_feature_bc_matrix/clean_barcodes.tsv.gz

        if [[ $paired == "TRUE" ]];then
            $python $src/visium_hd_atac/snapatac2_preprocess.py \
            --input_bam $outdir/align/${sampleid}.sorted.bam \
            --output_dir $outdir/fragments \
            --sampleid $sampleid \
            --species $species \
            --max_iter 1 \
            --n_features 50000 \
            --barcode_tag $res \
            --min_fragments_n 1 \
            --is_paired \
            --tissue_barcode $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/filtered_feature_bc_matrix/clean_barcodes.tsv.gz
        else
            $python $src/visium_hd_atac/snapatac2_preprocess.py \
                --input_bam $outdir/align/${sampleid}.sorted.bam \
                --output_dir $outdir/fragments \
                --sampleid $sampleid \
                --species $species \
                --max_iter 1 \
                --n_features 50000 \
                --barcode_tag $res \
                --min_fragments_n 1 \
                --tissue_barcode $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/filtered_feature_bc_matrix/clean_barcodes.tsv.gz
        fi 


    done 

    ls $outdir/fragments/*metadata.txt | while read meta_file;do 
        prefix_sample=$(basename -s ".metadata.txt" $meta_file)
        $Rscript $src/atac_QC.R 1 $meta_file $outdir/fragments/$prefix_sample.qc.pdf
    done 

}


function spatial_position(){
    if [[ ! -d $outdir/spatial ]];then 
        mkdir -p $outdir/spatial
    fi 

    for res in "CB" "LS";do
        $python $create_gene_activity \
            --input_h5ad $outdir/fragments/${sampleid}_${res}.h5ad \
            --species $species \
            --min_cells 0 \
            --min_genes 0

        $Rscript $createSeuratObj \
            --input_h5ad $outdir/fragments/${sampleid}_${res}.gene_activity.h5ad \
            --metadata_file $outdir/fragments/${sampleid}_${res}.metadata.txt \
            --img_dir $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/spatial \
            --outdir $outdir/spatial/
    done 
}


function bulk(){
    ### calculate as bulk samples
    if [[ ! -d $outdir/bulk ]];then 
        mkdir -p $outdir/bulk
    fi 
   
    $picard MarkDuplicates \
        -I $outdir/align/${sampleid}.sorted.bam \
        -O $outdir/bulk/${sampleid}.rmdup.bam \
        -M $outdir/bulk/${sampleid}.dedup.txt \
        -REMOVE_DUPLICATES true \
        -READ_NAME_REGEX null \
        --TMP_DIR ${outdir}/bulk

    $samtools index $outdir/bulk/${sampleid}.rmdup.bam
    ## filter the chrM reads
    $samtools idxstats -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.rmdup.bam \
        | cut -f 1 | grep -v MT \
        | xargs $samtools view -b $outdir/bulk/${sampleid}.rmdup.bam > $outdir/bulk/${sampleid}.clean.bam
    
    $samtools index -@ $SLURM_CPUS_PER_TASK $outdir/bulk/${sampleid}.clean.bam

    effect_genome_size=2652783500
    
    $bamCoverage --numberOfProcessors $SLURM_CPUS_PER_TASK \
        --binSize 10 \
        --normalizeUsing RPGC \
        --effectiveGenomeSize $effective_genome_size \
        --bam $outdir/bulk/${sampleid}.clean.bam \
        -o $outdir/bulk/${sampleid}.clean.bw

    $macs2 callpeak \
        -f BAM \
        -g ${MACS2_GENOME[$species]} \
        --nomodel --shift -100 --extsize 200 \
        --keep-dup all --qvalue 0.01 \
        -t $outdir/bulk/${sampleid}.clean.bam \
        -n $sampleid \
        --outdir $outdir/bulk

}

function signac_pipe(){


    res="CB"
    $Rscript $run_signac \
        --input_file $outdir/spatial/${sampleid}.extended_fragments.decontaminated.fragments.tsv.gz \
        --spatial_dir $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/spatial \
        --metadata_file $outdir/fragments/${sampleid}_${res}.metadata.txt \
        --outdir $outdir/spatial \
        --sample_name ${sampleid}."clean" \
        --genome $species \
        --tag $res \
        --n_cores $SLURM_CPUS_PER_TASK

    res="LS"

    $Rscript $run_signac \
        --input_file $outdir/align/${sampleid}.sorted.bam \
        --spatial_dir $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/spatial \
        --metadata_file $outdir/fragments/${sampleid}_${res}.metadata.txt \
        --outdir $outdir/spatial \
        --sample_name $sampleid.LS \
        --genome $species \
        --tag $res \
        --n_cores $SLURM_CPUS_PER_TASK

}

function stat(){

    if [[ ! -d $outdir/stat ]];then 
        mkdir -p $outdir/stat 
    fi 
     bam="$outdir/bulk/${sampleid}.clean.bam"
    peaks="$outdir/bulk/${sampleid}_peaks.narrowPeak"

    # check file
    if [ ! -s $bam ]; then
        echo $bam " not exist"
        exit
    fi

    if [ ! -s $peaks ]; then
        echo $peaks "peaks not exist"
        exit
    fi

    echo "→ Computing FRiP for $sampleid …"

    # 1) total reads
    total_reads=$(samtools view -c -@ 12 "$bam")

    # 2) reads in peaks
    reads_in_peaks=$( \
        $bedtools sort -i "$peaks" \
        | $bedtools merge -i stdin \
        | $bedtools intersect -u -nonamecheck \
            -a "$bam" \
            -b stdin -ubam \
        | samtools view -c \
    )

    # 3) 计算 FRiP（保留四位小数）
    frip=$(awk 'BEGIN{printf "%.4f", '$reads_in_peaks'/'$total_reads'}')

    total_raw_reads=$(grep Total $outdir/barcode/${sampleid}.barcode_stat.txt | awk '{print $2}')
    valid_barcode_reads=$(grep Valid $outdir/barcode/${sampleid}.barcode_stat.txt | awk '{print $2}')

    valid_barcode_percent=$(echo "scale=2; $valid_barcode_reads / $total_raw_reads * 100" | bc | xargs)
    reads_passing_filter=$(grep 'output":' $outdir/trim/${sampleid}.trimming_report.txt | awk '{print $2}' | head -n 1 | sed 's/,//g')
    reads_passing_filter_rate=$(echo "scale=2; $reads_passing_filter / $valid_barcode_reads * 100" | bc | xargs)
    
    unique_align_reads=$($samtools view -q 20 -c -@ 12 $outdir/align/${sampleid}.sorted.bam | xargs)

    align_rate=$(echo "scale=2; $unique_align_reads / $reads_passing_filter * 100" | bc | xargs)

    if [[ ! -s ${outdir}/stat/stat.txt ]]; then
        echo -e "SampleID\tSpecies\tTotal_reads\tBarcode_valid_percent\tReads_high_qualtity_percent\tUnique_aligned_reads\tUnique_align_rate\tFRiP" > ${outdir}/stat/stat.txt
    fi

    echo -e "$sampleid\t${species}\t" \
        "${total_raw_reads}\t" \
        "${valid_barcode_percent}%\t" \
        "${reads_passing_filter_rate}%\t" \
        "${unique_align_reads}\t" \
        "${align_rate}\t" \
        "${frip}" \
        >>${outdir}/stat/stat.txt

}


function cal_fragment_len(){

    cal_length="${src}/cal_length.py"
    $python $cal_length \
        -b $outdir/align/${sampleid}.sorted.bam \
        -t CB \
        -o $outdir/stat/${sampleid}.CB.median_lengths.tsv \
        -c $SLURM_CPUS_PER_TASK

}
function cal_swap_score(){


    res="L8"
    $Rscript $run_signac \
        --input_file $outdir/align/${sampleid}.sorted.bam \
        --spatial_dir $outdir/${sampleid}/outs/binned_outputs/square_${resolution_list[$res]}/spatial \
        --metadata_file $outdir/fragments/${sampleid}_${res}.metadata.txt \
        --outdir $outdir/spatial \
        --sample_name $sampleid.L8 \
        --genome $species \
        --tag $res \
        --n_cores $SLURM_CPUS_PER_TASK

    bash $swap_count \
        $outdir/spatial/${sampleid}.L8.extended_fragments.tsv.gz \
        >> ${outdir}/stat/swap_${res}.txt

}



set -x 


case "$option" in
pipe)
    run_spaceranger
    barcode_calling
    trim_fq
    align
    snapATAC2
    spatial_position
    bulk
    stat_abortive
    stat
    ;;
align)
    align
    ;;
barcode)
    barcode_calling
    ;;
QC)
    cal_fragment_len
    ;;
atac)
    signac_pipe
    ;;
dedup)
    dedup
    ;;
bulk)
    bulk
    ;;
dedup_UMI)
    dedup_UMI
    ;;
spatial)
    spatial_position
    ;;
run_spaceranger)
    run_spaceranger
    ;;
*)
    echo "unknown parameter:" $1
    helpdoc
    exit 1
    ;;
esac
